### DISCUSSION TITLE
Fine-grained privileges on every objects types

### DISCUSSION THREAD

**Discussion by bersace** [dalibo/ldap2pg#638] [General]
I'm sharing a proposal to manage fine-grained privileges in ldap2pg.

To manage privileges, ldap2pg loops on database and schema. But sometime, that would be nice to loop on other objects like table, views, procedures, etc.

An idea on this would be to be able to define generic object inspection:

``` yaml
postgres:
  object_queries:
    database: …
    schema: …
    object: …
```

When granting a privilege, one can append extra parameter. Matching object type will be used.

``` yaml
- grant:
    privilege: select_on_table
    database: …
    schema: …
    object: __all__
```

Privilges can use object type in grant and revoke queries:

``` yaml
privileges:
  select_on_table:
    grant: GRANT SELECT ON TABLE {object} IN SCHEMA {schema} TO {role};
    revoke: REVOKE SELECT ON TABLE {object} IN SCHEMA {schema} FROM {role};
```

`__select_on_all_tables__` could be rewritten like this, saving huge query to inspect.

Feedback welcome :-)
