### DISCUSSION TITLE
using parent key and filter

### DISCUSSION THREAD

**Discussion by fchapuis0101** [dalibo/ldap2pg#658] [Q&A] [answered]
Hi, I want to do some filter on search ldap result. But it seams it does not work parent: "{memberOf.cn}" dn: "ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch" This does not filter the memberOf.cn for the specific path

Any help will be very appreciate

Fabrice

```
version: 6

postgres:
  managed_roles_query: |
    select rolname from pg_roles where rolname ~ 'user_[12][0-9]{5}'
rules:
- description: "Synchronise admin users"
  ldapsearch:
    base: ou=org,ou=Users,dc=test,dc=comp,dc=ch
    filter: >
        (&
           (!(test))(memberOf=cn=*,ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch)
        )
    scope: "sub"
  roles:
  - name: "{myid}"
    options:
      LOGIN: true
      CONNECTION LIMIT: 10
    parent: "{memberOf.cn}"
      dn: "ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch"
    comment: "{myid}"
```

**Comment by bersace** [comment]
Bonjour,

À quoi correspond `dn: "ou=APP...` ? ça ne me semble même pas du YAML valide.

**Comment by fchapuis0101** [comment]
Merci pour ce retour. C'est en effet un essai de ma part, en vérifiant dans la doc ldap2pg la clé "parent" ne possède pas d'attributs. Je cherche à filtrer les memberOf.cn en fonction d'un chemin précis du ldap en l'occurence ici celui qui correspond à l'environnement de DEV et pas les autres. Comment effectuer cette configuration dans le ldap2pg.yml

**Reply by bersace** [reply]
C'est une question purement de recherche LDAP. Je retournerai la requête:

``` yaml
rules:
  - ldapsearch:
      base: ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch
      scope: sub
    roles:
      - name: "{cn}"
      - name: "{member.cn}"
        options: LOGIN
```

C'est gênant si vous avez des groupes de groupes (*nested groups*).
Si vous utilisez `member.sAMAccountName` plutôt que `member.cn`, vous aurez une explosion du nombre de recherches.

Sinon, vous devrez lister explicitement chaque objet sous `ou=APP`.
Si vous avez besoin d'une configuration dynamique, générez là avec un script avant de la passer à ldap2pg avec `--config=-` par exemple. Ça se fait.

cf. https://ldap.com/ldap-filters/

**Comment by fchapuis0101** [comment]
Merci pour votre réponse
En fait la requête LDAP retourne l'ensemble des utilisateurs pour un environnement donnée (développement par exempale)
-> cette requête est ok
Ensuite il faut que pour chaque utilisateur, j'obtienne les groupes auxquel il appartient, c'est là que c'est plus compliqué
la clé parent permet d'affecter un groupe à l'utilisateur dans la base Postgres.
`parent: "{memberOf.cn}"`
Le problème est que memberOf.cn retourne l'ensemble des groupes pour tous les environnements.
Il faudrait pouvoir générer une sous-requête pour chaque utilisateur avec un nouveau filtre sur ou=DEV pour retourner les bons groupes. 
Comment écrire cette sous-requête dans la configuration yaml du ldap2pg?

**Reply by bersace** [reply]
Il faut traiter le problème dans l'autre sens : lister les groupes dans un environnement et créer les membres de ces groupes uniquement.

**Comment by fchapuis0101** [comment]
Oui, c'est une bonne idée, j'ai essayé de prendre le problème par l'autre bout (code ci-dessous). Mais comment récupérer les attributs des utilisateurs qui se trouvent dans les feuilles d'une autre branche du ldap, il faut aussi une sous requête? Il n'y a pas moyen d'écrire une 2ème requête de recherche? (avec le mot clé joins peut-être)

```
version: 6

postgres:
  managed_roles_query: |
    select rolname from pg_roles where rolname ~ 'user_[12][0-9]{5}'
rules:
- description: "Synchronise admin users"
  ldapsearch:
    base: ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch
    scope: "sub"
  roles:
  - name: "{uniqueMember.uid}"
    options:
      LOGIN: true
      CONNECTION LIMIT: 10
```

**Reply by bersace** [reply]
`{uniqueMember.uid}` ne déclenche pas de sous-recherche LDAP car ldap2pg présume qu'uid fait partie du DN.
Soit utiliser un RDN soit utiliser un attribut qui ne peut être dans un DN comme `sAMAccountName`.

**Reply by fchapuis0101** [reply]
la requête retourne un ensemlbe d'attributs uniqueMember et uniqueMember.uid représent le nom de l'utilisateur. Comment utiliser un RDN?, il va permettre de pointer automatiquement sur la branche de l'arbre qui contient les utilisateurs? Pouvez me donner un exemple de code avec un RDN.
Merci pour votre aide

**Reply by bersace** [reply]
Pour la recherche LDAP

``` ldif
uniqueMember: uid=toto,ou=Users,dc=bridoulou,dc=ch
```

ldap2pg sait récupérer le rdn `uid` avec la substitution `{uniqueMember.uid}`, c'est à dire `toto` dans ce cas. Si `uid` n'est pas dans le DN de l'utilisateur, alors ldap2pg échouera.

**Reply by fchapuis0101** [reply]
oui mais comment à partir de l'attribut uniqueMember.uid (toto) se repositionner dans la branche des utilisateurs `ou=org,ou=Users,dc=test,dc=comp,dc=ch`

**Reply by bersace** [reply]
Pour récupérer quel attribut ? `sAMAccountName` ? `memberOf` ?

En partant de l'exemple suivant, que vous manque-t-il ?

``` yaml
rules:
- ldapsearch:
    base: ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch
  roles:
    - name: "{cn}"
    - name: "{uniqueMember.uid}"
      parent: "{cn}"
```

**Reply by fchapuis0101** [reply]
il me manque les propriétés de l'utilisateur 
` name: "{uniqueMember.uid}"` donne par exemple toto
après pour récupréer les proprités de toto if faut accèder à l'ou
`ou=org,ou=Users,dc=test,dc=comp,dc=ch`
branche dans laquelle se trouve tous les utilsateurs avec leurs propritétés

**Reply by bersace** [reply]
Quelles propriétés ?

À noter, on peut définir plusieurs fois un rôles, la parents sont aggrégés.

**Reply by fchapuis0101** [reply]
par exemple: son numéro d'employé, son nom complet etc... Ces informations ne sont pas dans la branche où se trouvent les groupes

**Reply by fchapuis0101** [reply]
Bonjour,
Je vais résumer ce que je souhaite obtenir avec ldap2pg
1. Une 1ère requête ldap permet d'obtenir la liste des identifiants des utilisateurs qui appartiennent aux groupes dev
`base: ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch`
2. Une 2ème requête ldap pour obtenir les propriétés pour chaque utilisateur 
`base: ou=org,ou=Users,dc=test,dc=comp,dc=ch`
Est-ce qu'il est possible de construire ce type d'interrogation dans la configuration ldap2pg?

**Reply by bersace** [reply, marked as answer]
Bonjour @fchapuis: ça doit être possible.

À noter : vous pouvez définir des liens de parenté en plusieurs fois. La première règle définira les options. Les suivantes ajouteront des parents.

``` yaml

rules:
  - description: Créer les utilisateurs
    ldapsearch:
      base: ou=org,ou=Users,dc=test,dc=comp,dc=ch
     role: ...
  - description: Accorder l'accès dev
    ldapsearch:
      base: ou=APP,ou=DEV,ou=700_group,ou=20_group,ou=Other,ou=xxx,dc=test,dc=comp,dc=ch
       ...
     role:
       name: "{uniqueMember.uid}"
       parent: "{cn}"
```

Étienne
