### DISCUSSION TITLE
How to alter default permissions by schema?

### DISCUSSION THREAD

**Discussion by dectris-jacs** [dalibo/ldap2pg#704] [Q&A]
I would like to be able to assign LDAP users read permissions to future tables in a given schema. I have tried to do this in a couple different ways that have not worked. Here are simplified examples of my `ldap2pg.yml`

```yaml
version: 6
    
postgres:
  roles_blacklist_query:
    - postgres
    - ...
privileges:
  default_ro:
  - __connect__           
  - __usage_on_schemas__  
  - __select_on_tables__  
  - __select_on_sequences__
  - __usage_on_sequences__ 
rules:
- roles:
  - name: readers
  grant:
    - privilege: default_ro
      role: readers
      database: db1
      schemas: [schema1, schema2]
- description: "Synchronize LDAP Users"
  ldapsearch:
    base: "OU=xxx,OU=yyy,DC=zzz,DC=aaa"
    filter: "(&(objectClass=person)(memberOf=CN=nnnn,OU=mmm,OU=aaaa,DC=bbbb,DC=cccc))"
  roles:
  - name: "{sAMAccountName}"
    comment: "LDAP user {sAMAccountName}"
    options: LOGIN
    parent: readers
```
```yaml
version: 6
    
postgres:
  roles_blacklist_query:
    - postgres
    - ...
privileges:
  default_ro:
  - __connect__           
  - __usage_on_schemas__  
  - __select_on_tables__  
  - on: SCHEMA DEFAULT
    type: SELECT
    object: TABLES
rules:
- roles:
  - name: readers
  grant:
    - privilege: default_ro
      role: readers
      database: db1
      schemas: [schema1, schema2]
- description: "Synchronize LDAP Users"
  ldapsearch:
    base: "OU=xxx,OU=yyy,DC=zzz,DC=aaa"
    filter: "(&(objectClass=person)(memberOf=CN=nnnn,OU=mmm,OU=aaaa,DC=bbbb,DC=cccc))"
  roles:
  - name: "{sAMAccountName}"
    comment: "LDAP user {sAMAccountName}"
    options: LOGIN
    parent: readers
```
```yaml
version: 6
    
postgres:
  roles_blacklist_query:
    - postgres
    - ...
privileges:
  default_ro:
  - __connect__           
  - __usage_on_schemas__  
  - __select_on_tables__  
  - __default_select_on_tables__
rules:
- roles:
  - name: readers
  grant:
    - privilege: default_ro
      role: readers
      database: db1
      schemas: [schema1, schema2]
- description: "Synchronize LDAP Users"
  ldapsearch:
    base: "OU=xxx,OU=yyy,DC=zzz,DC=aaa"
    filter: "(&(objectClass=person)(memberOf=CN=nnnn,OU=mmm,OU=aaaa,DC=bbbb,DC=cccc))"
  roles:
  - name: "{sAMAccountName}"
    comment: "LDAP user {sAMAccountName}"
    options: LOGIN
    parent: readers
```
None of these configurations have worked when a new table has been added and attempted to be read by a given user. In my DDLs I would write something like 

```sql
ALTER DEFAULT PRIVILEGES IN SCHEMA schema1 GRANT SELECT ON TABLES TO user;
```

What is the equivolent to this using LDAP2PG?
