### ISSUE TITLE
Generate role with sAMAccountName from each user of a group

### ISSUE THREAD

**Issue by EagleEnergy** [dalibo/ldap2pg#128]
Hi,
We have already sharing about my problem with @bersace.
So you send me this config for sync_map:

``` yaml
- ldap:
    base: ou=users,ou=site,ou=oncodesign,dc=ldap,dc=local 
    attributes: sAMAccountName
  roles:
  - name_attribute: sAMAccountName
    options: LOGIN
- ldap:
    base: ou=groups,ou=site,ou=oncodesign,dc=ldap,dc=local 
    attributes: [groupname, members]
  roles:
  - name_attribute: groupname
    options: NOLOGIN
    member_attribute: members
```

I had adapted this config like this:

``` yaml
- ldap:
    base: ou=users,ou=site,ou=oncodesign,dc=ldap,dc=local
    filter: "(objectClass=User)"
    attributes: sAMAccountName
  roles:
    name_attribute: sAMAccountName
    options: LOGIN
- ldap:
    base: ou=groups,ou=site,ou=oncodesign,dc=ldap,dc=local
    filter: "(cn=NameofGroup)"
    attributes: [member, cn]
  roles:
    name_attribute: member
    options: NOLOGIN
    member_attribute: cn
```

I had change "groupename and member" attributes because they are not recognized by AD.

So after start ldap2pg in dry mode, the script would create role for all users in OU Users but not only users member of my specified group.

Maybe I need to extract CN user from a first research to the group and next creat a sync_map for each user returned to take his sAMAccountName for create a role with this name. But I don't know how to do this.

Thanks for support :)

**Comment by bersace** [comment]
I'm thinking of a *join* feature to generate member lists. Something like:


  ``` yaml
# warning: just a mock
- ldap:
    base: …
    attributes: cn, member
    join:
      reference: member
      attribute: sAMAccountName
  roles:
  - name_attribute: cn
    member_attribute: join.sAMAccountName
  - name_attribute:  join.sAMAccountName
```

**Comment by EagleEnergy** [comment]
I don't know if this is the right usage for your configuration but if I try like this:
```
- ldap:
  base: ou=groups,ou=site,ou=oncodesign,dc=ldap,dc=local
  filter: "(cn=NameofGroup)"
  attributes: cn, member
  join:
    reference: member
    attribute: sAMAccountName
roles:
- name_attribute: cn
  member_attribute: join.sAMAccountName
- name_attribute:  join.sAMAccountName
```
the script was in error:


```
[ldap2pg.script      ERROR] Unhandled error:
[ldap2pg.script      ERROR] Traceback (most recent call last):
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 75, in main
[ldap2pg.script      ERROR]     exit(wrapped_main(config))
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 23, in wrapped_main
[ldap2pg.script      ERROR]     config.load()
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 599, in load
[ldap2pg.script      ERROR]     self.merge(file_config=file_config, environ=os.environ, args=args)
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 619, in merge
[ldap2pg.script      ERROR]     args=args,
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 414, in process
[ldap2pg.script      ERROR]     return self.processor(value)
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 269, in syncmap
[ldap2pg.script      ERROR]     maplist[:] = [mapping(m) for m in maplist]
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 269, in <listcomp>
[ldap2pg.script      ERROR]     maplist[:] = [mapping(m) for m in maplist]
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 178, in mapping
[ldap2pg.script      ERROR]     value['ldap'] = ldapquery(value['ldap'])
[ldap2pg.script      ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/config.py", line 86, in ldapquery
[ldap2pg.script      ERROR]     query = dict(Configuration.DEFAULTS['ldap']['default_query'], **value)
[ldap2pg.script      ERROR] TypeError: type object argument after ** must be a mapping, not NoneType
[ldap2pg.script      ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
linuxadmin@SRV-DEV-UBUNTU:~$ nano ldap2pg.yml
```
