### ISSUE TITLE
ACL configuration for create rights GRANT 

### ISSUE THREAD

**Issue by EagleEnergy** [dalibo/ldap2pg#129]
Hi so sorry I don't understand how to use ACL for generate GRANT options I need for my roles.

I have created this groups in my Active Directory:

Database1_ro
Database1_rw
Database2_ro
Database2_rw
Global_rw
Global_ro

So for exemple each users in Database1_ro need to have read privileges on Database1 only.
I think I need to generate this: GRANT CONNECT ON Database1 TO rolename.

I have use this acl:

```
acl_dict:
  all-tables-select:
    # Warning: schema with no tables are never granted!
    inspect: |
      WITH
      namespace_tables AS (
        -- All namespace and role having grant on it, and array of available
        -- relations in the namespace.
        SELECT

nsp.nspname,
          ARRAY(
            SELECT UNNEST(array_agg(rel.relname)
            FILTER (WHERE rel.relname IS NOT NULL))
            ORDER BY 1
          ) AS tables
        FROM pg_catalog.pg_namespace nsp
        LEFT OUTER JOIN pg_catalog.pg_class rel
          ON rel.relnamespace = nsp.oid AND relkind IN ('r', 'v')
        WHERE nspname NOT LIKE 'pg_%'
        GROUP BY 1
      ),
      tables_grants AS (
        SELECT
          table_schema AS "schema",
          grantee,
          -- Aggregate the relation grant for this privilege.
          ARRAY(SELECT UNNEST(array_agg(table_name::name)) ORDER BY 1) AS tables
        FROM information_schema.role_table_grants
        WHERE privilege_type = 'SELECT'
        GROUP BY 1, 2
      )
      SELECT
        nspname, rolname,
        rels.tables = nsp.tables AS "full"
      FROM namespace_tables nsp
      CROSS JOIN pg_catalog.pg_roles rol
      JOIN tables_grants rels
        ON rels."schema" = nsp.nspname AND rels.grantee = rolname
    grant: |
      GRANT CONNECT ON Database1 TO {role};
    #revoke: |
      #REVOKE SELECT ON ALL TABLES IN SCHEMA {schema} FROM {role};

```
With this group definition:

```
acl_groups:
  ro: [all-tables-select]
```

And use this grant configuration in group mapping:

```
  grant:
    role_attribute: sAMAccountName
    acl: ro
    database: Database1
    schema: __all__
```

 from the exemple of the cookbook.
But there  are no privilèges declared in my Database1 and there no error when I run ldap2pg.

Somebody can help me?

**Comment by bersace** [comment]
Hi @EagleEnergy 

I suggest you to define ACL at group level.

``` yaml
- role:
    name: Database1_ro
  grant:
    role: Database1_ro
    database: Database1
    acl: ro
- ldap:
    base: …
  role:
    name_attribute: …
    parent: Database1
```

You may want to use `role_match` parameter as described at http://ldap2pg.readthedocs.io/en/latest/config/#grant-parameters

**Comment by EagleEnergy** [comment]
This change nothing or I use it unproperly.

To understand, I propose to you to generate the good config for just one user and next when is validated trying to addapt for my case :)  Sorry but the ACLs are trouble for me.

So I have foudn this "simple" acl :
```
acl_dict:
  connect:
    inspect: |
      WITH d AS (
          SELECT
              (aclexplode(datacl)).grantee AS grantee,
              (aclexplode(datacl)).privilege_type AS priv
          FROM pg_catalog.pg_database
          WHERE datname = current_database()
      )
      SELECT NULL as namespace, r.rolname
      FROM pg_catalog.pg_roles AS r
      JOIN d ON d.grantee = r.oid AND d.priv = 'CONNECT'
    grant: |
      GRANT CONNECT ON DATABASE {database} TO {role};
    revoke: |
      REVOKE CONNECT ON DATABASE {database} FROM {role}
```

And try to affect it for user in sync_map:


```
- ldap:
    base: ou=users,dc=ldap,dc=local
    filter: (objectClass=User)"
    scope: sub
    attribute: sAMAccountName
  role:
    name_attribute: sAMAccountName
    options: LOGIN
  grant:
    role_attribute: sAMAccountName
    acl: connect
```

So can you explain to me why this didn't working?
I think is a the simplest definition to learn how it's working.

But maybe it's possible to only define a grant command without using ACLs?
