### ISSUE TITLE
sync_map user with with ROLE postgreadmin and  SUPERUSER  role

### ISSUE THREAD

**Issue by canlar** [dalibo/ldap2pg#142]
Hi,

i am testing and have removed from ldap group one user.
i want that ONLY ldapgroup member AND postgresadmins member should be sync.

If i run ldap2pg the deleted user from ldapgroup was not deleted from postgres.
And it will be recreate the already exist user and give error.

```
[ldap2pg.script    WARNING] Running in dry mode. Postgres will be untouched.
[ldap2pg.manager      INFO] Inspecting Postgres...
[ldap2pg.psql        DEBUG] Connecting to Postgres postgres://postgres:password@host.de.company.cnb:5432/postgres.
[ldap2pg.psql        DEBUG] Doing: SELECT datname FROM pg_catalog.pg_database
[ldap2pg.psql        DEBUG] WHERE datallowconn IS TRUE ORDER BY 1;
[ldap2pg.psql        DEBUG] Doing: SELECT
[ldap2pg.psql        DEBUG]     role.rolname, array_agg(members.rolname) AS members,
[ldap2pg.psql        DEBUG]     role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper
[ldap2pg.psql        DEBUG] FROM
[ldap2pg.psql        DEBUG]     pg_catalog.pg_roles AS role
[ldap2pg.psql        DEBUG] LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
[ldap2pg.psql        DEBUG] LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
[ldap2pg.psql        DEBUG] WHERE role.rolsuper IS TRUE AND role.rolname='postgresadmins'
[ldap2pg.psql        DEBUG] GROUP BY role.rolname, role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper
[ldap2pg.psql        DEBUG] ORDER BY 1;
[ldap2pg.manager     DEBUG] Found role u'postgresadmins' SUPERUSER NOBYPASSRLS NOCREATEDB INHERIT NOREPLICATION NOCREATEROLE NOLOGIN.
[ldap2pg.manager     DEBUG] Role postgresadmins has members user1,user2.
[ldap2pg.manager     DEBUG] Postgres inspection done.
[ldap2pg.manager     DEBUG] Working on schema __all__.__any__.
[ldap2pg.manager     DEBUG] Found role postgresadmins from YAML.
[ldap2pg.manager     DEBUG] Working on schema __all__.__any__.
[ldap2pg.manager      INFO] Querying LDAP cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=company,DC=cnb...
[ldap2pg.ldap        DEBUG] Doing: ldapsearch -x -W -b cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=company,DC=cnb -s sub '(objectClass=*)' member
[ldap2pg.manager     DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager     DEBUG] Found role user1 from CN=manager,OU=Groups,OU=IAM,OU=_DomainOperations,DC=company,DC=cnb member.CN.
[ldap2pg.manager     DEBUG] LDAP inspection completed. Post processing.
[ldap2pg.role        DEBUG] Add user1 as member of postgresadmins.
[ldap2pg.psql        DEBUG] Using Postgres connection to postgres://postgres:password@host.de.company.cnb:5432/postgres.
[ldap2pg.manager      INFO] Would create user1.
[ldap2pg.manager     DEBUG] Would execute: CREATE ROLE user1 WITH NOSUPERUSER NOBYPASSRLS NOCREATEDB INHERIT NOREPLICATION NOCREATEROLE LOGIN;
[ldap2pg.role        DEBUG] Role postgresadmins has spurious members user2.
[ldap2pg.psql        DEBUG] Using Postgres connection to postgres://postgres:password@host.de.company.cnb:5432/postgres.
[ldap2pg.manager      INFO] Would delete spurious postgresadmins members.
[ldap2pg.manager     DEBUG] Would execute: REVOKE postgresadmins FROM user2;
[ldap2pg.manager     DEBUG] Generated 2 querie(s).
[ldap2pg.script       INFO] Comparison complete.
[ldap2pg.psql        DEBUG] Closing Postgres cursor to postgres://postgres:password@host.de.company.cnb:5432/postgres.
[ldap2pg.psql        DEBUG] Closing Postgres connexion to postgres://postgres:password@host.de.company.cnb:5432/postgres.
```

without dry modus logfile  it gives me CRITICAL ERROR

```
[ldap2pg.manager      INFO] Create user1.
[ldap2pg.psql        DEBUG] Doing: CREATE ROLE user1 WITH NOSUPERUSER NOBYPASSRLS NOCREATEDB INHERIT NOREPLICATION NOCREATEROLE LOGIN;
[ldap2pg.script   CRITICAL] Error while executing SQL query:
[ldap2pg.script   CRITICAL] role "user1" already exists
```

config file

``` yaml
# List of glob patterns to exclude external roles.
  blacklist: [postgres, pg_*]

#Synchronize ONLY Superusers/DB Admins
#we don't touch application user
  roles_query: |
    SELECT
        role.rolname, array_agg(members.rolname) AS members,
        {options}
    FROM
        pg_catalog.pg_roles AS role
    LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
    LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
    WHERE role.rolsuper IS TRUE AND role.rolname='postgresadmins'
    GROUP BY role.rolname, {options}
    ORDER BY 1;

sync_map:
- role:
    name: POSTGRESADMINS
    options: NOLOGIN SUPERUSER

- ldap:
    base: "cn=manager,ou=Groups,ou=IAM,ou=_DomainOperations,DC=ccompany,DC=cnb"
    scope: sub
    attribute: member
  role:
    name_attribute: member.CN
    options: LOGIN
    parents: [POSTGRESADMINS]
```

Why ldap2pg will create user1 because it existing in ldap and postgres.
