### ISSUE TITLE
Users in multiple ldap groups are assigned to only one postgresql group

### ISSUE THREAD

**Issue by dirks** [dalibo/ldap2pg#156]
I have the following scenario:
- multiple databases
- database a should be writable by users from ldap group 1
- database b should be writable by users from ldap group 2
- there are users which are in both groups

I tried to realize this with the following ldap2pg.yml

```yaml
---
color: yes
verbose: yes
dry: no

ldap:
    uri: ldap://example.com
    binddn: cn=svc.ldap,ou=Functional Users,ou=Users,dc=example,dc=com
    password: "redacted"

postgres:
    blacklist: [postgres, pg_*, testing]

acls:
  ro:
  - __usage_on_schemas__
  - __select_on_tables__
  rw:
  - ro
  - __insert__
  - __update_on_tables__
  ddl:
  - rw
  - __all_on_schemas__
  - __all_on_tables__

sync_map:
    __all__:
    - roles: [test1_writer,test1_reader,test2_writer,test2_reader]
      options: NOLOGIN

    test01:
    - ldap:
        base: ou=justatest,dc=example,dc=com
        filter: "(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-test,ou=FunctionalGroups,ou=Groups,ou=justatest,dc=idiv,dc=de)"
        attributes: sAMAccountName
      roles:
        name_attribute: sAMAccountName
        options: LOGIN
        parent: test1_writer
      grant:
        - acl: rw
          database: test1
          role: test1_writer

    test02:
    - ldap:
        base: ou=justatest,dc=example,dc=com
        filter: "(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-test2,ou=FunctionalGroups,ou=Groups,ou=justatest,dc=idiv,dc=de)"
        attributes: sAMAccountName
      roles:
        name_attribute: sAMAccountName
        options: LOGIN
        parent: test2_writer
      grant:
        - acl: rw
          database: test2
          role: test2_writer
```

Expected behaviour:
- users in cn=g_r_postgres01-test and cn=g_r_postgres01-test2 end up in test1_writer and test2_writer
- users which are in cn=g_r_postgres01-test only end up in test1_writer
- users which are in cn=g_r_postgres01-test2 only end up in test2_writer

Actual behaviour:
- users in cn=g_r_postgres01-test and cn=g_r_postgres01-test2 end up in test2_writer but not in test1_writer
- users which are in cn=g_r_postgres01-test only end up in test1_writer
- users which are in cn=g_r_postgres01-test2 only end up in test2_writer

I did not find an append flag or similar in the documentation. Is there another way to realize this?

p.s. The memberOf:1.2.840.113556.1.4.1941 is used to recursively get members from AD which are in nested ldap groups.
