### ISSUE TITLE
acls not cycled over pg_catalog by default

### ISSUE THREAD

**Issue by dirks** [dalibo/ldap2pg#165]
I tried to follow along the examples in the documentation to create a group of ddl users. But they are not able to create a database:

```SQL
exampledb=> create table test(f1 int);
ERROR:  permission denied for schema pg_catalog
LINE 1: create table test(f1 int);
```

Granting usage on pg_catalog schema resolves the issue.

```SQL
grant USAGE on SCHEMA pg_catalog to ldap_test;
```

```YAML
postgres:
    blacklist: [postgres, pg_*, testing]

acls:
  ro:
  - __connect__
  - __usage_on_schemas__
  - __select_on_tables__

  rw:
  - ro
  - __insert__
  - __update_on_tables__

  ddl:
  - rw
  - __all_on_schemas__
  - __all_on_tables__


sync_map:
    __all__:
    - roles: [ldap_test]

    exampledb:
    - ldap:
        base: ou=AAI,dc=example,dc=com
        filter: "(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-test,ou=FunctionalGroups,ou=Groups,ou=MYORG,dc=example,dc=com)"
        attributes: sAMAccountName
      roles:
        name_attribute: sAMAccountName
        options: LOGIN
        parent: ldap_test
      grant:
        - acl: ddl
          database: exampledb
          role: ldap_test
```

It seems that acls are not applied to schema pg_catalog, neither default nor when explicitly stating `schema: __all__`. Applying an acl explictly to pg_catalog works, e.g. adding the following acl to the above grants

```
        - acl: ro
          database: exampledb
          schema: pg_catalog
          role: ldap_test
```
