### ISSUE TITLE
Simple ACL example

### ISSUE THREAD

**Issue by joshlk** [dalibo/ldap2pg#170]
Hi,

I would like to control permissions of the objects in Postgres. Our scenario is that we have one database and I would like all objects (tables, schemas ...) to be accessible to all. My current conf is (the ACL bit is taken from the [cookbook](https://ldap2pg.readthedocs.io/en/latest/cookbook/#read-only-read-write-ddl-groups)):

```
acls:
  ro:
  - __usage_on_schemas__
  - __select_on_tables__

  rw:
  - ro
  - __all_on_tables__

  ddl:
  - rw
  - __create_on_schemas__

sync_map:
  - roles:
    - names: [owners, readers, writers]
      options: NOLOGIN
      database: company

  - grant:
    - acl: ro
      database: company
      schema: __all__
      role: readers

    - acl: rw
      database: company
      schema: __all__
      role: writers

    - acl: ddl
      database: company
      schema: __all__
      role: owners

  - ldap:
      base: "OU=People,OU=company,DC=int,DC=company,DC=com"
      attributes: sAMAccountName
    role:
      name_attribute: sAMAccountName
      options: LOGIN NOSUPERUSER NOCREATEDB
      parent: owners
    grant:
      - acl: ddl
        role: owners
```

As you can see above, all LDAP users are being asinged to the `ddl` group, however, when I run it it prevents users from logging in using pgadmin 4. I have tried a few variations of the above and got errors like (from postgresql.log):
1.
```
2018-01-25 18:28:06.141 UTC [20822] joshlk@postgres ERROR:  permission denied for function version
2018-01-25 18:28:06.141 UTC [20822] joshlk@postgres STATEMENT:  SELECT version()
```

2.
```
2018-01-25 18:25:23.306 UTC [20810] joshlk@postgres ERROR:  permission denied for schema pg_catalog at character 143
2018-01-25 18:25:23.306 UTC [20810] joshlk@postgres STATEMENT:
	SELECT
	    oid as id, rolname as name, rolsuper as is_superuser,
	    rolcreaterole as can_create_role, rolcreatedb as can_create_db
	FROM
	    pg_catalog.pg_roles
	WHERE
	    rolname = current_user
```

3.
```
2018-01-25 18:47:00.433 UTC [21181] joshlk@postgres ERROR:  permission denied for schema pg_catalog
2018-01-25 18:47:00.433 UTC [21181] joshlk@postgres STATEMENT:  SELECT CASE WHEN usesuper
	       THEN pg_is_in_recovery()
	       ELSE FALSE
	       END as inrecovery,
	       CASE WHEN usesuper AND pg_is_in_recovery()
	       THEN pg_is_xlog_replay_paused()
	       ELSE FALSE
	       END as isreplaypaused
	FROM pg_user WHERE usename=current_user
```

It looks like it is because of its locking users out from accessing the postgres default database and objects within it. Can I ask ldap2pg to exclude revoking permissions on the posgres database?

Do you have any recommendations on what ACL rules to use? What I want to prevent is someone creating a table or schema and then the rest of the team not been able to access it. My team is small so something simple would suffice.

Bonus question... is there a way that when a user is created a schema of the same name is also created? So for user `joshlk` it automatically creates a schema `joshlk`?

Many thanks for your help and really appreciate your work and giving to the open source community!

Josh

**Comment by bersace** [comment]
Hi @joshlk 

There is a bug in 4.2 around `pg_catalog`, do you use latest release ?

Some notes about your YAML:

- `database` is useless in `role` rules. It's for `grant`
- You grant twice `ddl` to `owners`. Actually, it's granted one per LDAP entry.

About creating schema, it's a good idea. I'm thinking of a `sql:` rule that accept a free SQL snippet and `ldap2pg` injects LDAP attributes into it and execute it on one or more database. You can open a feature request for that.

**Comment by joshlk** [comment]
Thanks. I’m using v4.1. What version should I roll back to?

Josh

**Comment by bersace** [comment]
@joshlk 4.4 is good

**Comment by joshlk** [comment]
v4.3.1 is currently the latest 😃  Do you mean that or wait until the next version

**Comment by joshlk** [comment]
Just upgraded to v4.3.1 and using this conf:

```
acls:
  ro:
  - __usage_on_schemas__
  - __select_on_tables__

  rw:
  - ro
  - __all_on_tables__

  ddl:
  - rw
  - __create_on_schemas__

sync_map:
  - roles:
    - names: [owners, readers, writers]
      options: NOLOGIN

  - grant:
    - acl: ro
      database: company_db
      schema: __all__
      role: readers

    - acl: rw
      database: company_db
      schema: __all__
      role: writers

    - acl: ddl
      database: company_db
      schema: __all__
      role: owners

  - ldap:
      base: "OU=company,DC=int,DC=outra,DC=co,DC=uk"
      attributes: sAMAccountName
    role:
      name_attribute: sAMAccountName
      options: LOGIN NOSUPERUSER NOCREATEDB
      parent: owners
```

And when navigating the `company_db` database in pgadmin 4 and trying to view the public schema I get this error (from postresql.log):
```
2018-01-26 10:25:33.957 UTC [27123] joshlk@company_db ERROR:  permission denied for schema pg_catalog at character 636
2018-01-26 10:25:33.957 UTC [27123] joshlk@company_db STATEMENT:  SELECT
	    nsp.nspname as schema_name,
	    (nsp.nspname = 'pg_catalog' AND EXISTS
	        (SELECT 1 FROM pg_class WHERE relname = 'pg_class' AND
	            relnamespace = nsp.oid LIMIT 1)) OR
	    (nsp.nspname = 'pgagent' AND EXISTS
	        (SELECT 1 FROM pg_class WHERE relname = 'pga_job' AND
	            relnamespace = nsp.oid LIMIT 1)) OR
	    (nsp.nspname = 'information_schema' AND EXISTS
	        (SELECT 1 FROM pg_class WHERE relname = 'tables' AND
	            relnamespace = nsp.oid LIMIT 1)) AS is_catalog,
	    CASE
	    WHEN nsp.nspname = ANY('{information_schema}')
	        THEN false
	    ELSE true END AS db_support
	FROM
	    pg_catalog.pg_namespace nsp
	WHERE
	    nsp.oid = 2200::OID;
```

Any ideas? Should I wait until the next release? Thanks again for your help 👍

**Comment by bersace** [comment]
@joshlk right, it's 4.3.1 . should have named it 4.4. sorry :/

Can you send me some verbose logs of ldap2pg ?

**Comment by joshlk** [comment]
So I created a new database cluster and ran a dry run using the same config as above. I installed v4.3.1 from PyPi but the logs states v4.1 🙃

Here is the log output using the flag `-vv`
[ldap2pg_1.log](https://github.com/dalibo/ldap2pg/files/1667538/ldap2pg_1.log)

**Comment by bersace** [comment]
```
[ldap2pg.config       INFO] Starting ldap2pg 4.1.
```

Yes, it's 4.1. You must have 4.3.1 in logs. Do you have multiple version installed ? One in /usr/bin and the other in /usr/local/bin ? Use `locate` or something like that to check this.

**Comment by joshlk** [comment]
Thanks not sure why v4.1 was installed but thanks for spotting. v4.3.1 is now installed. 

This is my current test process:

1. I start a fresh cluster `sudo pg_createcluster 9.6 main`
2. Create a database `company_db` using the role `postgres`
3. Using the below config run ldap2pg:

```yaml
acls:
  ro:
  - __usage_on_schemas__
  - __select_on_tables__

  rw:
  - ro
  - __all_on_tables__

  ddl:
  - rw
  - __all_on_schemas__

sync_map:
  - roles:
    - names: [owners, readers, writers]
      options: NOLOGIN

  - grant:
    - acl: ro
      database: company_db
      schema: __all__
      role: readers

    - acl: rw
      database: company_db
      schema: __all__
      role: writers

    - acl: ddl
      database: company_db
      schema: __all__
      role: owners

  - ldap:
      base: "OU=people,DC=int,DC=company,DC=com"
      attributes: sAMAccountName
    role:
      name_attribute: sAMAccountName
      options: LOGIN NOSUPERUSER NOCREATEDB
      parent: owners
```

The newly created LDAP accounts can browse and create tables, functions and types, but, they can't create a new schema. However, if I change the ownership of the `comapny_db` database to `owners` instead of `postgres` the users can create new schemas. Success 🚀 

I think that's it thanks!! Do you have any other tips on configuring ownership?
