### ISSUE TITLE
Create schema of same name when user is created

### ISSUE THREAD

**Issue by joshlk** [dalibo/ldap2pg#171]
It common to have a schema that the same name as a user in a database. By default, postgres  includes such a schema in its `search_path` automatically, see "[section 5.8.3](https://www.postgresql.org/docs/9.6/static/ddl-schemas.html)" in the docs.

It would be ace to have an option in ldap2pg that would create a schema of the same name when a user is newly created.

Thanks

**Comment by bersace** [comment]
Hi @joshlk actually, you can already do this by hacking the ACL mechanism :-) Just think `grant` as `create` and `revoke` as `drop`. This should look like:

```
acls:
  user_schema:
    type: datacl
    inspect: |
      SELECT NULL as "schema", rolename
      FROM pg_namespace n
      JOIN pg_authid ON rolname = nspname
    grant: |
      CREATE SCHEMA {role};
      ALTER USER {role} SET search_path {role},public;
```

YMMV

**Comment by bersace** [comment]
I'm thinking of extending ldap2pg to help managing this case. Here is an idea:

``` yaml
- role:
    name: '{cn}'
    on_create: |
      CREATE SCHEMA {role};
    on_alter: |
      ALTER SCHEMA {old} RENAME TO {new};
    on_drop: |
      DROP SCHEMA {role} CASCADE;
```

What do you think of it ? Would you prefer global `on_create`, `on_drop` ? Thanks for the feedback.
