### ISSUE TITLE
Using parents_attribute results in more PostgreSQL grants than it should

### ISSUE THREAD

**Issue by schmandr** [dalibo/ldap2pg#210]
I'm trying to create login roles and assigning them to a group they are a member of according to LDAP. I set up the following LDAP query (_group1_, _group2_ and _group3_ are created beforehand with another LDAP query):

```
- ldap:
    base: ou=groups,dc=ldap,dc=xy,dc=org
    filter: "(|(cn=group1)(cn=group2)(cn=group3))"
  role:
    name_attribute: memberUid
    options: LOGIN
    parent:
    - ldap_roles
    parents_attribute: cn
```

This basically works. Members of LDAP _group1_ are granted PostgreSQL role _group1_.
However, members of LDAP _group2_ are granted PostgreSQL roles _group2_ **and** _group1_.
And members of LDAP _group3_ are granted PostgreSQL roles _group3_ **and** _group2_ and _group1_.

Is it a bug, or am I doing something wrong?
