### ISSUE TITLE
Issue in creating user roles 

### ISSUE THREAD

**Issue by aditya-2203** [dalibo/ldap2pg#218]
```
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/spare/local/infrad/m2/lib/python2.7/site-packages/ldap2pg/script.py", line 88, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/spare/local/infrad/m2/lib/python2.7/site-packages/ldap2pg/script.py", line 68, in wrapped_main
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/spare/local/infrad/m2/lib/python2.7/site-packages/ldap2pg/manager.py", line 198, in sync
[ldap2pg.script       ERROR]     ldaproles, ldapacl = self.inspect_ldap(syncmap)
[ldap2pg.script       ERROR]   File "/spare/local/infrad/m2/lib/python2.7/site-packages/ldap2pg/manager.py", line 155, in inspect_ldap
[ldap2pg.script       ERROR]     for grant in grants:
[ldap2pg.script       ERROR]   File "/spare/local/infrad/m2/lib/python2.7/site-packages/ldap2pg/manager.py", line 120, in apply_grant_rules
[ldap2pg.script       ERROR]     role = role.lower()
[ldap2pg.script       ERROR] AttributeError: 'dict' object has no attribute 'lower'
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

My LDAP File

```
---
acls:
  ro:
  - __connect__
  - __select_on_all_tables__
  - __select_on_all_sequences__
  - __default_select_on_tables__
  - __default_select_on_sequences__
postgres:
  dsn: "postgres://*:*@machine.new:5432/trade"
  databases_query: [trade]
  schemas_query: [public]
  blacklist : [postgres, pg_*, root,trade_rw]
sync_map:
  grant:
    schema : public
    database : trade
    acl: ro
    roles:
    - name_attribute: cn
      options: NOLOGIN
      member_attribute: memberUid
    - name_attribute: memberUid
      options: LOGIN
  ldap:
    base: "cn=readers,ou=Group,dc=microsoft,dc=com"
```

I want to create individual roles for each of the user returned. I have no role defined in database. i am getting the above error.

**Comment by bersace** [comment]
Hi @aditya-2203 , thanks for the report !

`ldap2pg` should be more explicit about the error.

The error is in the YAML : you mixed `grant` and `role` rules. They are separates, just like `CREATE ROLE` and `GRANT` in SQL.

``` yaml
acls:
  ro:
  - __connect__
  - __select_on_all_tables__
  - __select_on_all_sequences__
  - __default_select_on_tables__
  - __default_select_on_sequences__

postgres:
  dsn: "postgres://*:*@machine.new:5432/trade"
  databases_query: [trade]
  schemas_query: [public]
  blacklist : [postgres, pg_*, root,trade_rw]

sync_map:
- ldap:
    base: "cn=readers,ou=Group,dc=microsoft,dc=com"
  roles:
    - name_attribute: cn
      options: NOLOGIN
      member_attribute: memberUid
    - name_attribute: memberUid
      options: LOGIN
  grant:
    schema : public
    database : trade
    acl: ro
    role_attribute: cn
```

See : http://ldap2pg.readthedocs.io/en/latest/config/#sync_map
