### ISSUE TITLE
"Failed to process [...],DC=org: Unknown attribute 'samaccountname'"

### ISSUE THREAD

**Issue by jrjsmrtn** [dalibo/ldap2pg#224]
I have the following ldap2pg.yml:

```
ldap:
  uri: ldap://localhost:389/

sync_map:
- ldap:
    base: cn=Users,dc=cxptc,dc=org
  role:
    name_attribute: sAMAccountName
    options: LOGIN
```

Any sync attempt fails with a "Failed to process [...],DC=org: Unknown attribute 'samaccountname'", whatever the case used for the name_attribute. The same with "userPrincipalName".

My config is: ldap2pg 4.10, psycopg2 2.6.2, python-ldap 3.1.0 and Python 3.5.3 on Debian 9.4. LDAP (Samba AD DC 4.8.2-debian) and PostgreSQL (9.6.7) are on the same host and anonymous LDAP searches are enabled.

**Comment by jrjsmrtn** [comment]
Correction: ldap2pg is installed with pip3 from the git master.

**Comment by bersace** [comment]
Hi @jrjsmrtn . Thanks for reporting !

Can you run `ldap2pg -v`  ? Beware, the output is very verbose. You'll see `ldapsearch` commands. Can you report it ?

Also, can you adapt it, run it and report the LDIF output ?

**Comment by jrjsmrtn** [comment]
OK, I found the issue: as there was no filter on the sAMAccountName or userPrincipalName attribute, the LDAP search was returning some entries with no such attributes. Hence the error message make sense.

I tested successfully with sAMAccountName and userPrincipalName:
```
- ldap:
    base: cn=Users,dc=cxptc,dc=org
    filter: '(userPrincipalName=*)'
  role:
    name_attribute: userPrincipalName
    options: LOGIN
```

Thanks :-)
