### ISSUE TITLE
default privileges can't be determined error

### ISSUE THREAD

**Issue by testingash** [dalibo/ldap2pg#230]
Hi,
I reached next level by first using ldapsearch and then getting parameters correct. But next I came across this below:

```
ldap2pg.yml.
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP cn=developers-group,ou=d... (objectclass...
Would create ash12.
Would create ashle.
Would create tt.
Would create developers-group.
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Unhandled error:
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/ldap2pg/script.py", line 84, in main
exit(wrapped_main(config))
File "/usr/local/lib/python3.4/dist-packages/ldap2pg/script.py", line 68, in wrapped_main
count = manager.sync(syncmap=config['sync_map'])
File "/usr/local/lib/python3.4/dist-packages/ldap2pg/manager.py", line 213, in sync
pgacl = self.inspector.fetch_grants(schemas, pgmanagedroles)
File "/usr/local/lib/python3.4/dist-packages/ldap2pg/inspector.py", line 254, in fetch_grants
rows = psql(privilege.inspect)
File "/usr/local/lib/python3.4/dist-packages/ldap2pg/psql.py", line 142, in call
self.cursor.execute(query, *args)
psycopg2.ProgrammingError: syntax error at or near "("
LINE 26: FILTER (WHERE pro.proname IS NOT NULL) AS procs
^
Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

Here I am giving ldap2pg.yml:

``` yaml
postgres:
  dsn: postgres://****:pass123@localhost:5432/
  databases_query: [postgres]

privileges:
  # Define an privilege group `ro` with read-only grants
  ro:
  - __connect__
  - __execute__
  - __select_on_tables__
  - __select_on_sequences__
  - __usage_on_schemas__
  - __usage_on_types__

sync_map:
- ldap:
    base: cn=*,ou=*,dc=ldap,dc=com
    filter: (objectclass=*)
  role:
    name: '{cn}'    
    options: LOGIN SUPERUSER
```

Any help would be appreciated.

**Comment by bersace** [comment]
Can you tell the postgres cluster version ?

**Comment by bersace** [comment]
Ok, i reproduced the bug. I'm working on it.

**Comment by bersace** [comment]
@testingash the fix is merged in master, and 9.3 is tested on CI. Can you confirm this ? Can you test installing a from master ?

**Comment by testingash** [comment]
@bersace I downloaded from master. 
Starting ldap2pg 4.11.
....
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP cn=developers-group,ou=d... (objectclass...
Would create  ash12.
Would create  ashle.
Would create  tt.
Would create developers-group.
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Can't inspect privilege mypriv: query not defined.
Would grant mypriv on postgres.information_schema to admin.
Would grant mypriv on postgres.pg_catalog to admin.
Would grant mypriv on postgres.pg_temp_1 to admin.
Would grant mypriv on postgres.pg_toast to admin.
Would grant mypriv on postgres.pg_toast_temp_1 to admin.
Would grant mypriv on postgres.public to admin.
Comparison complete.
Fix worked.thank you.

**Comment by testingash** [comment]
@bersace : one thing I would like to ask is Will this tool will be helpful if I want to create same LDAP users in postgres?? This case is for already created users in LDAP server. In my understanding this tool will work as hook to get LDAP users. Please correct me if I am misunderstand tool.

**Comment by bersace** [comment]
> Will this tool will be helpful if I want to create same LDAP users in postgres?? 

Yes, for sure. It's the purpose of ldap2pg. See http://ldap2pg.readthedocs.io/en/latest/roles/ .

Postgres knows how to check password using LDAP protocol. Postgres does not know how to query LDAP and create roles. ldap2pg allows you to describe how to create roles in Postgres cluster according to a centralized directory, using LDAP. Since a user creation is complete with it's default privileges, ldap2pg helps you to manage privileges too.

**Comment by bersace** [comment]
@testingash ldap2pg 4.12 is now on PyPI with the fix, so you don't have to use master.

**Comment by testingash** [comment]
thanks for information. I mean by this "Will this tool will be helpful if I want to create same LDAP users in postgres?? " -- Is I want to create/update table in postgres with those LDAP users.

**Comment by bersace** [comment]
>  I want to create/update table in postgres with those LDAP users.

Ok, sorry, I misunderstood. For a role to be allowed to create a table it must have `__create_on_schemas__` privilege granted alias `CREATE ON SCHEMA` as well as `__insert_on_tables__` in schema `pg_catalog`.

``` yaml
privileges:
  rw: [__instert_on_tables__]
  ddl: [__create_on_schemas__]
sync_map:
- grant:
  - privilge: rw
    schema: pg_catalog
    role: creators
  - privilege: ddl
    schema: myschema
    role: creators
```

YMMV
