### ISSUE TITLE
Generic object loop

### ISSUE THREAD

**Issue by bersace** [dalibo/ldap2pg#269]
I'm sharing a proposal to manager fine-grained privileges in ldap2pg.

To manage privileges, ldap2pg loops on database and schema. But sometime, that would be nice to loop on other objects like table, views, procedures, etc.

An idea on this would be to be able to define generic object inspection:

``` yaml
postgres:
  object_queries:
    database: …
    schema: …
    table: …
    views:
    fdw: …
```

When granting a privilege, one can append extra parameter. Matching object type will be used.

``` yaml
- grant:
    privilege: select_on_table
    database: …
    schema: …
    table: __all__
```

Privilges can use object type in grant and revoke queries:

``` yaml
privileges:
  select_on_table:
    grant: GRANT SELECT ON TABLE {table} IN SCHEMA {schema} TO {role};
    revoke: REVOKE SELECT ON TABLE {table} IN SCHEMA {schema} FROM {role};
```

`__select_on_all_tables__` could be rewritten like this, saving huge query to inspect.
