### ISSUE TITLE
Allow for empty AD group in LDAP sync

### ISSUE THREAD

**Issue by andersbogsnes** [dalibo/ldap2pg#282]
We have an issue where we mirror ldap2pg.yaml across our environments, (test, dev, prod) and have a similar naming scheme for our AD groups.

```yaml
  - ldap:
      base: "base_dn_goes_here"
      filter: "(CN=${ENV}_name_of_ad_group)" # Replaced at runtime with ENV
    role:
      name: '{member.cn}'
      options: LOGIN SUPERUSER
      parent:
        - ldap_roles
        - owners
      on_unexpected_dn: warn
```

The problem occurs when there are no users in the AD group - something that can also occur if someone quits. ldap2pg will error out saying it has no attribute `member`. 

As far as I can see, there is no way to have ldap2pg ignore an AD group with no members.
I have tried "on_unexpected_dn" but that does not seem to work in this case.

**Comment by bersace** [comment]
Hi @andersbogsnes, thanks for the report.

`on_unexpected_dn` is meant to tell ldap2pg how to manage recursion, not missing attribute.

Could you add a filter that exclude entry without member attribute ? It's hard for ldap2pg to distinguish a missing attribute from a typo in attribute name.

**Comment by andersbogsnes** [comment]
@bersace Thanks for the swift reply!

I'm not sure how that filter would work - if the filter returns empty, then it will never have a member attribute and I would get the same error, no? Or does ldap2pg handle that case differently?

**Comment by bersace** [comment]
Hi @andersbogsnes , having `(member=*)` will return no entry instead of an incomplete set. This give me an idea. Maybe ldap2pg could automatically add LDAP filter, but that would defeat the debugging of mispelled attributes.

On empty set, ldap2pg just do nothing. As usual, ldap2pg drops managed roles not returned by directory.

Is it clearer for you ?

**Comment by andersbogsnes** [comment]
Just to spell it out for someone not well-versed in ldap queries :-)

So I would change my ldap section to this?

```yaml
  - ldap:
      base: "base_dn_goes_here"
      filter: "(&(CN=${ENV}_name_of_ad_group)(member=*))" # Replaced at runtime with ENV
    role:
      name: '{member.cn}'
      options: LOGIN SUPERUSER
      parent:
        - ldap_roles
        - owners
      on_unexpected_dn: warn
```

**Comment by bersace** [comment]
Yep, this looks good. Thanks for the sharing !

**Comment by andersbogsnes** [comment]
Thanks for the help!

**Comment by meegoSVK** [comment]
Hello.
Would it be possible to implement that do nothing on empty group as you mentioned earlier?

> Hi @andersbogsnes , having `(member=*)` will return no entry instead of an incomplete set. This give me an idea. Maybe ldap2pg could automatically add LDAP filter, but that would defeat the debugging of mispelled attributes.
> 
> On empty set, ldap2pg just do nothing. As usual, ldap2pg drops managed roles not returned by directory.
> 
> Is it clearer for you ?

I wanted to use ldap2pg to synchronize our AD with several postgresql engines.
We have a policy, that we have groups that are intentionaly empty on creation.
For example we do not want to delete users from applications/databases and preserve their groups.
But when someone leaves for example for maternity leave or. longer period of time from our comapy, he becomes disabled in AD and he becomes a member of group called group_database_disabled.
Members of these groups get rejected by pg_hba.conf
`host database +database_disabled 0.0.0.0/0 reject`

When I got YAML like:
```
- ldap:
    base: OU=server01,OU=PGSQL,OU=Groups,OU=Company,DC=ad,DC=company,DC=org
    filter: "(cn=group_pgsql_*)"
    scope: sub
    joins:
      member:
        filter: "(member=*)"
  roles:
  - names:
    - '{member.sAMAccountName}'
    options: LOGIN
    parent:
    - '{cn}'
    - ldap_users
    on_unexpected_dn: fail
    comment: "User account from AD -  User {member.displayName}."
```
everything works fine, until an empty group is found in LDAP - ldap2pg crashes because no member is there.


Whe I tried @andersbogsnes workaround without ${ENV}_name_of_ad_group it works only when any user is not in two groups.
In that case, both groups have all members of each of them even when they are not in both in AD.

YAML:
```
- ldap:
    base: OU=server01,OU=PGSQL,OU=Groups,OU=Company,DC=ad,DC=company,DC=org
    filter: "(&(cn=group_pgsql_*)(member=*))"
  roles:
  - names:
    - '{member.sAMAccountName}'
    options: LOGIN
    parent:
    - '{cn}'
    - ldap_users
    on_unexpected_dn: fail
    comment: "User account from AD -  User {member.displayName}."
```

Example:

```
AD group: CN=group_pgsql_database1_ro,OU=server01,OU=PGSQL,OU=Groups,OU=Company,DC=ad,DC=company,DC=org
Members: User_01, User_02
AD group: CN=group_pgsql_database1_ro,OU=server01,OU=PGSQL,OU=Groups,OU=Company,DC=ad,DC=company,DC=org
Members: User_03, User_04, User_02
AD group: CN=group_pgsql_database1_disabled,OU=server01,OU=PGSQL,OU=Groups,OU=Company,DC=ad,DC=company,DC=org
Members: none
```

Result in Postgres is:

```
User_01  |  | {ldap_users,group_pgsql_database1_ro,group_pgsql_database1_rw}
User_02  |  | {ldap_users,group_pgsql_database1_ro,group_pgsql_database1_rw}
User_03  |  | {ldap_users,group_pgsql_database1_ro,group_pgsql_database1_rw}
User_04  |  | {ldap_users,group_pgsql_database1_ro,group_pgsql_database1_rw}
group_pgsql_database1_disabled | Cannot login | {ldap_groups}
group_pgsql_database1_ro | Cannot login | {ldap_groups}
group_pgsql_database1_rw | Cannot login | {ldap_groups}
```

Could you please add an option to ldap2pg, something like you alredy have -> on_unexpected_dn?
It could be an option something like on_empty_group and it could be failing or skipping.

Thank you very much in advance!

**Comment by bersace** [comment]
Hi @meegoSVK . That's fair.

Just thinking loud. What do you think of something like:

``` yml
sync_map:
- ldap:
    base: ...
    on_unexpected_dn: fail
    allow_missing_attributes: [member]
```

This is so common that this could be the default. Maybe with a warning message.

``` console
$ ldap2pg ...
...
INFO: Query LDAP to create superusers.                               
INFO: Querying LDAP ou=groups,dc=ldap,dc=lda... (cn=dba)...
WARN: No member attribute returned for cn=group_pgsql_.... Considering an empty list.
...
```

What do you think of this ? Both of you :-)

**Comment by meegoSVK** [comment]
Hi @bersace 
That would be awesome!

**Comment by andersbogsnes** [comment]
Looks good to me! Seems like a very useful feature, and the warning is definitely a good way to avoid foot-guns!

Is there a flag for treating warnings as errors if the user wants to run in “strict mode” ala Sphinx?

**Comment by bersace** [comment]
Hi @andersbogsnes treating warnings as error is a good idea. I suggest you to open an issue or maybe complete this to #286

**Comment by bersace** [comment]
Hu, that's odd. There ldap2pg already defaults missing attributes to `[]`.

https://github.com/dalibo/ldap2pg/blob/master/ldap2pg/manager.py#L59

**Comment by andersbogsnes** [comment]
> Hi @andersbogsnes treating warnings as error is a good idea. I suggest you to open an issue or maybe complete this to #286

Created #338

**Comment by meegoSVK** [comment]
Hi @bersace !

Thanks for implementing missing attributes.
But it looks like I am missing something :(

I tried using allow_missing_attributes, but I always get:
```
[ldap2pg.script       CRITI] Missing join result for member.
```

Here is YAML:

```
sync_map:
# First, setup static roles and grants
- roles:
  - names:
    - ldap_admins
    - ldap_users
    - ldap_groups
    options: NOLOGIN
    comment: "Groups created for LDAP synchronization."

# Now query LDAP to create roles and grant them privileges by parenting.
# Create admins
- ldap:
    base: OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info
    allow_missing_attributes: []
    filter: "(cn=sgrp_pgsql_admins)"
  role:
    name: '{member.cn}'
    options: LOGIN SUPERUSER CREATEROLE CREATEDB
    parent:
    - ldap_admins
    comment: "Superuser account from AD - User {member.displayName}"
    on_unexpected_dn: warn

# Create roles from specific OU
- ldap:
    base: OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info
    allow_missing_attributes: []
    filter: "(cn=sgrp_pgsql_*)"
  role:
    name: '{cn}'
    options: NOLOGIN
    parent:
    - ldap_groups
    comment: "Mastered by Identity management"
    on_unexpected_dn: warn

# Fill roles from specific OU with users - if any
- ldap:
    base: OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info
    allow_missing_attributes: [member]
    filter: "(cn=sgrp_pgsql_*)"
    scope: sub
    joins:
      member:
        allow_missing_attributes: []
        filter: "(objectClass=User)"
  role:
    name: '{member.sAMAccountName}'
    options: LOGIN
    parent:
    - '{cn}'
    - ldap_users
    on_unexpected_dn: warn
    comment: "User account from AD -  User {member.displayName}."
```

Here is output from verbose mode:

```
[ldap2pg.manager       INFO] Querying LDAP OU=tst_ou,OU=PGSQL,OU... (cn=sgrp_pgs...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(cn=sgrp_pgsql_*)' member cn
[ldap2pg.manager      DEBUG] Got 6 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=sgrp_pgsql_tst_ou_app_1_disabled,OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager      WARNI] Missing 'member' from CN=sgrp_pgsql_tst_ou_app_2_disabled,OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager      WARNI] Missing 'member' from CN=sgrp_pgsql_tst_ou_app_3_disabled,OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager       INFO] Sub-querying LDAP CN=USR115036,OU=ext...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b CN=USR115036,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(objectClass=User)' displayName sAMAccountName
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=USR115036,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager       INFO] Sub-querying LDAP CN=USR115020,OU=ext...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b CN=USR115020,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(objectClass=User)' displayName sAMAccountName
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=USR115020,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager       INFO] Sub-querying LDAP CN=USR115015,OU=ext...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b CN=USR115015,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(objectClass=User)' displayName sAMAccountName
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=USR115015,OU=external,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager       INFO] Sub-querying LDAP CN=USR00125,OU=Primary...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b CN=USR00125,OU=Primary,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(objectClass=User)' displayName sAMAccountName
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=USR00125,OU=Primary,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager       INFO] Sub-querying LDAP CN=USR00123,OU=Primary...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D CN=pgsqlsynchro,OU=Special_Users,DC=ad,DC=mydomain,DC=info -W -b CN=USR00123,OU=Primary,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info -s sub '(objectClass=User)' displayName sAMAccountName
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from CN=USR00123,OU=Primary,OU=Users,OU=My_Domain,DC=ad,DC=mydomain,DC=info. Considering it as an empty list.
[ldap2pg.manager      DEBUG] Want role USR115036 in LDAP.
[ldap2pg.manager      DEBUG] Want role USR115020 in LDAP.
[ldap2pg.manager      DEBUG] Want role USR115015 in LDAP.
[ldap2pg.manager      DEBUG] Want role USR00125 in LDAP.
[ldap2pg.manager      DEBUG] Want role USR00123 in LDAP.
[ldap2pg.script       CRITI] Missing join result for member.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.
```

This happens when it tires to query empty group.
I know, I can make special `-ldap` entry for every group, but this is what I want to avoid and have "automatized".

Thanks for help, and sorry for reopening old wounds :)

**Comment by meegoSVK** [comment]
Hi @bersace 

I found out, that querying for `{member.displayName}` and `{member.sAMAccountName} makes the problem.

So when I change the YAML to:
```
# Fill roles from specific OU with users - if any
- ldap:
    base: OU=tst_ou,OU=PGSQL,OU=Groups,OU=My_Domain,DC=ad,DC=mydomain,DC=info
    allow_missing_attributes: [member]
    filter: "(cn=sgrp_pgsql_*)"
    scope: sub
    joins:
      member:
        allow_missing_attributes: []
        filter: "(objectClass=User)"
  role:
    name: '{member.cn}'
    options: LOGIN
    parent:
    - '{cn}'
    - ldap_users
    on_unexpected_dn: warn
    comment: "User account from AD -  User."
```

Everything works fine.
But I am missing the displayName in comment, and I have to rely on that sAMAccountName is same as CN.
