### ISSUE TITLE
Blacklist does not affect users loaded from AD Groups

### ISSUE THREAD

**Issue by andersbogsnes** [dalibo/ldap2pg#283]
Related to #282 

When creating LDAP roles, I would expect the blacklist to also apply to any users found there, in effect skipping them. This does not appear to be the case today.

**Comment by bersace** [comment]
Hi @andersbogsnes ,

Can you paste me a sample of `blacklist` and debug logs of ldap2pg ? Can you give me steps to reproduce ?

Regards,

**Comment by andersbogsnes** [comment]
Of course - just wanted to check if this was intended functionality or not :-)

# blacklist
```yaml
postgres:
  # Blacklist POSTGRES_USER as they already exist with their rights
  blacklist:
    - 'postgres'
    - 'pg_*'
    - 'xulmdwz1'
    - 'xtlmdwz1'
    - 'xplmdwz1'
```

# Logs ldap2pg:
```
Starting ldap2pg 4.18.
Reading configuration from stdin.
Running in real mode.
Inspecting roles in Postgres cluster...
Querying LDAP OU=ApplResources,OU=Grou... (CN=udvk_LM_...
Querying LDAP OU=ApplResources,OU=Grou... (CN=udvk_LM_...
Querying LDAP OU=ApplResources,OU=Grou... (CN=udvk_LM_...
Create abanbn.
Create abjets.
Create abthhk.
Create abthrp.
Create xulmdwz2.
Create xulmdwz1.
Error while executing SQL query:
role "xulmdwz1" already exists
2019/07/02 07:50:02.258549 [ERR] (cli) unexpected exit from subprocess (1)
```
# Logs postgres
```
2019-07-02 07:45:02.680 UTC [111200] STATEMENT:  CREATE ROLE "xulmdwz1" WITH NOBYPASSRLS LOGIN NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION SUPERUSER;
	COMMENT ON ROLE "xulmdwz1" IS 'Managed by ldap2pg.';
```


Create a new postgres database with POSTGRES_USER set to a user that exists in an AD group

Sample ldap2pg.yaml ldap section
```yaml
  - ldap:
      base: OU=ApplResources,OU=Groups,DC=alm,DC=brand,DC=dk
      filter: "(CN=${STAGE_ID}_LM_dw_ml_data_Admin)"
    role:
      name: '{member.cn}'
      options: LOGIN SUPERUSER
      parent:
        - ldap_roles
        - owners
      on_unexpected_dn: warn
```
# To reproduce

- Have an AD group with a user ABC in it.
- Create new postgres with POSTGRES_USER=ABC

    - `docker run -e POSTGRES_USER ABC -p 5432:5432 postgres`

- Run ldap2pg with template ldap2pg.yaml containing following ldap section
```yaml
  - ldap:
      base: "basedn"
      filter: "(CN=group_name"
    role:
      name: '{member.cn}'
      options: LOGIN SUPERUSER
      parent:
        - ldap_roles
        - owners
      on_unexpected_dn: warn
```

- ldap2pg will then fail with the message:
```
Error while executing SQL query:
role "ABC" already exists
```
