### ISSUE TITLE
Unknown attribute in my first ldap2pg.yml

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [dalibo/ldap2pg#290]
## What do you want?
This is my first attempt at using ldap2pg. I'm having trouble getting it working. I'm getting "Unknown attribute" for cn. What am I doing wrong? 

P.S.: thank you for this tool.

## ldap2pg.yml

``` yml
color: yes
dry: yes

postgres:
    dsn: postgres://postgres@localhost/
    blacklist: [postgres, pg_* ]
ldap:
    uri: ldap://ipa.domain:389
    binddn: cn=ldapadm,dc=domain
    password: P@ssw0rd
sync_map:
- ldap:
    base: ou=users,dc=domain
  grant:
    database: blog
    privilege: ro
    role: '{cn}'
...
```
### Log output
```
[ldap2pg.manager       INFO] Querying LDAP ou=users,dc=domain... (objectClass...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D cn=ldapadm,dc=domain -W -b ou=users,dc=domain -s sub '(objectClass=*)' cn
[ldap2pg.manager      DEBUG] Got 4 entries from LDAP.
[ldap2pg.script       CRITI] Failed to process (u'ou=users,dc=domain', {u'dn': : Unknown attribute u'cn'

```
### ldapsearch -x -D cn=ldapadm,dc=domain -W -b ou=users,dc=domain -s sub '(objectClass=*)' cn
```
# extended LDIF
#
# LDAPv3
# base <ou=users,dc=domain> with scope subtree
# filter: (objectClass=*)
# requesting: cn 
#

# users, domain
dn: ou=users,dc=domain

# bob, users, domain
dn: cn=bob,ou=users,dc=domain
cn: bob

# alice, users, domain
dn: cn=alice,ou=users,dc=domain
cn: alice

# blog, users, domain
dn: cn=blog,ou=users,dc=domain
cn: blog

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 4

```

**Comment by gi9obru0etuPlc6wozls** [comment]
It appears that adding objectclass=inetOrgPerson to the sync_map fixed the issue:
```
sync_map:
- ldap:
    base: ou=users,dc=domain
    filter: (objectclass=inetOrgPerson)
  role:
    name: '{cn}'
    options: LOGIN
```
