### ISSUE TITLE
Role inheritance  

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [dalibo/ldap2pg#293]
## What do you want?
I'm struggling with how to grant a role another role using the memberOf attribute of groupOfNames. I can get my ldap2pg.yml to manage the group and users create and drop, but I am failing at being able to do the grants. 

## ldap2pg.yml
``` yml
color: yes
dry: yes
verbosity: 5

postgres:
    dsn: postgres://postgres@localhost/
    blacklist: [postgres, pg_* ]
ldap:
    uri: ldap://ipa.domain:389
    binddn: cn=ldapadm,dc=domain
    password: P@ssw0rd
sync_map:
- ldap:
    base: ou=users,dc=domain
    filter: (objectclass=inetOrgPerson)
  role:
    name: '{cn}'
    options: LOGIN
- ldap:
    base: ou=groups,dc=domain
    filter: (objectclass=groupOfNames)
  role:
    name: '{cn}'
    options: NOLOGIN

```
### I'm trying to achieve:
```
grant b_g to a_g;
grant b_g to c_g;
grant a_g to d_g;
grant a_g to e_g;
grant d_g to a_u;
grant e_g to b_u;
grant c_g to c_u;
```
### ldapsearch -x -D cn=ldapadm,dc=domain -W -b ou=groups,dc=domain -s sub '(objectClass=*)' dn memberOf member
```
# extended LDIF
#
# LDAPv3
# base <ou=groups,dc=domain> with scope subtree
# filter: (objectClass=*)
# requesting: dn memberOf member 
#

# groups, domain
dn: ou=groups,dc=domain

# a_g, groups, domain
dn: cn=a_g,ou=groups,dc=domain
memberOf: cn=b_g,ou=groups,dc=domain
member: cn=d_g,ou=groups,dc=domain
member: cn=e_g,ou=groups,dc=domain

# b_g, groups, domain
dn: cn=b_g,ou=groups,dc=domain
member: cn=a_g,ou=groups,dc=domain
member: cn=c_g,ou=groups,dc=domain

# d_g, groups, domain
dn: cn=d_g,ou=groups,dc=domain
member: cn=a_u,ou=users,dc=domain
memberOf: cn=a_g,ou=groups,dc=domain

# c_g, groups, domain
dn: cn=c_g,ou=groups,dc=domain
member: cn=c_u,ou=users,dc=domain
memberOf: cn=b_g,ou=groups,dc=domain

# e_g, groups, domain
dn: cn=e_g,ou=groups,dc=domain
member: cn=b_u,ou=users,dc=domain
memberOf: cn=a_g,ou=groups,dc=domain

# search result
search: 2
result: 0 Success

# numResponses: 7
# numEntries: 6
```
### ldapsearch -x -D cn=ldapadm,dc=domain -W -b ou=users,dc=domain -s sub '(objectClass=*)' dn memberOf member
```
# extended LDIF
#
# LDAPv3
# base <ou=users,dc=domain> with scope subtree
# filter: (objectClass=*)
# requesting: dn memberOf member 
#

# users, domain
dn: ou=users,dc=domain

# a_u, users, domain
dn: cn=a_u,ou=users,dc=domain
memberOf: cn=d_g,ou=groups,dc=domain

# b_u, users, domain
dn: cn=b_u,ou=users,dc=domain
memberOf: cn=e_g,ou=groups,dc=domain

# c_u, users, domain
dn: cn=c_u,ou=users,dc=domain
memberOf: cn=c_g,ou=groups,dc=domain

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 4

```

**Comment by bersace** [comment]
I you use `cn` as role name, it should be simpler.

``` yaml
- ldap:
    base: ou=groups,dc=domain
    filter: (objectclass=groupOfNames)
  role:
    name: '{cn}'
    options: NOLOGIN
    members: '{member.cn}'
    parent: '{memberOf.cn}'
```

Let me know.
