### ISSUE TITLE
Comment on user for multiple users in one group uses the same displayName for every user in group

### ISSUE THREAD

**Issue by meegoSVK** [dalibo/ldap2pg#308]
Hi guys!
I got a minor issue while creating users with this unbelievable thing :)
When I want to comment users with member.displayName, it always takes the first name in the group and applies in all comments.

Lets say we got a group called pgsql_admins with 3 users:
ID05711 - Maverick Smith
ID22817 - Demarius White
ID46518 - Malcolm Young

```yaml
- ldap:
    base: OU=PGSQL,OU=company_name,DC=country
    filter: "(cn=pgsql_admins)"
  role:
    name: '{member.cn}'
    options: LOGIN SUPERUSER CREATEROLE CREATEDB
    parent:
    - ldap_admins
    comment: "Superusers - {member.displayName}"
    on_unexpected_dn: warn
```

The output looks like this:

```sql
               Role name                |                         Attributes                         |   Member of   |               Description
----------------------------------------+------------------------------------------------------------+---------------+------------------------------------------
 ID05711                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Maverick Smith
 ID22817                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Maverick Smith
 ID46518                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Maverick Smith
```

But I want an output like this:

```sql
               Role name                |                         Attributes                         |   Member of   |               Description
----------------------------------------+------------------------------------------------------------+---------------+------------------------------------------
 ID05711                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Maverick Smith
 ID22817                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Demarius White
 ID46518                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - Malcolm Young
```

The funny thing is, that even when I use:

```yaml
- ldap:
    base: OU=PGSQL,OU=company_name,DC=country
    filter: "(cn=pgsql_admins)"
  role:
    name: '{member.cn}'
    options: LOGIN SUPERUSER CREATEROLE CREATEDB
    parent:
    - ldap_admins
    comment: "Superusers - {member.cn}"
    on_unexpected_dn: warn

```

The outcome ist like this:

```sql
               Role name                |                         Attributes                         |   Member of   |               Description
----------------------------------------+------------------------------------------------------------+---------------+------------------------------------------
 ID05711                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - ID05711
 ID22817                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - ID05711
 ID46518                                | Superuser, Create role, Create DB                          | {ldap_admins} | Superusers - ID05711
```

Thanks for your help!
Sincerely
Meego

**Comment by bersace** [comment]
Hi, good catch. I'll work out this in the next weeks. I'm in vacation for now. Thanks for the report !

**Comment by bersace** [comment]
There is an issue with your need. Each parameter of role rules have different processing.

`parents` and `members` are lists, with static items or expanded from LDAP entry. Theses lists are cloned on each roles generated.

`names` is a list, with static items or expanded from LDAP entry, each item in the list generate a role.

`comment` is not a list. It is considered like `parents` and `members` : it is shared amongst all roles generated by the rule.

For example, how could LDAP know the right comment in the following role rule ?

``` yaml
- ldap: ...
  role:
    names:
    - "{cn}"
    - "{member.cn}"
    comment: "{cn}"
```

This rules generate one role for `cn` and one role for each `member.cn`. I'm open to suggestion.

**Comment by bersace** [comment]
Hi @meegoSVK . I think i came up with a solution. Here is the output from various rules combination. Would you mind to review it ?

``` console
$ python my-comment.py 
I: LDAP Entry: ('dn', {'dn': ['dn'], 'cn': ['cn'], 'member': ['m0', 'm1']}, {})
I: Rule {'names': ['static', 'dyn_{cn}'], 'comment': 'Dynamic comment {cn}'}.
I:    -> static - comment=Dynamic comment cn
I:    -> dyn_cn - comment=Dynamic comment cn
I: Done.
I: Rule {'names': ['dyn_{cn}'], 'comment': 'Dynamic comment {cn}'}.
I:    -> dyn_cn - comment=Dynamic comment cn
I: Done.
I: Rule {'names': ['dyn_{cn}'], 'comment': 'Static comment.'}.
I:    -> dyn_cn - comment=Static comment.
I: Done.
I: Rule {'names': ['dyn_{cn}'], 'comment': 'Dynamic Single {dn}'}.
I:    -> dyn_cn - comment=Dynamic Single dn
I: Done.
I: Rule {'names': ['dyn_multi_{member}'], 'comment': 'Dynamic Single {dn}'}.
I:    -> dyn_multi_m0 - comment=Dynamic Single dn
I:    -> dyn_multi_m1 - comment=Dynamic Single dn
I: Done.
$
```

Please report me a combination of entry, name and comment and what you would expect ?

Meanwhile, I'm starting to implement this in ldap2pg.

**Comment by bersace** [comment]
Ok, i found two edge case in which ldap2pg must fails :

``` console
I: Rule {'names': ['dyn_{cn}'], 'comment': 'Dynamic {member}'}.
I:    -> dyn_cn - comment=Dynamic m0
E: Fails: We have more comments than names!
I: Rule {'names': ['static'], 'comment': 'No comment {empty}'}.
E: Fails: Can't generate comment.
```

Are you ok with this behaviour ?

**Comment by bersace** [comment]
@meegoSVK 

``` yaml
  role:
    name: '{member.cn}'
    comment: "Superusers - {member.displayName}"
```

Note that `member.displayName` triggers a client-side LDAP subquery for each role. When running `ldap2pg --verbose`, you have a log line with the time spent querying LDAP directory :

```
[ldap2pg.script       DEBUG] Searching directory took 0:00:00.001544.
```

If synchronisation is slow, check this and avoid the sub-query by using `{member}` (the DN) or something that does not require subquery.
