### ISSUE TITLE
Using existing roles

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#315]
Hey Folks,

first: great work, thanks for doing this!

I have two issues:

1. I want to reuse already existing local roles and grant them to the new generated roles, so I right now use a custom privilege for that:

```
privileges:
  read:
    type: nspacl
    grant: 'GRANT test_read TO {role}'
    revoke: 'REVOKE test_read FROM {role}'

  app:
    type: nspacl
    grant: 'GRANT test_app TO {role}'
    revoke: 'REVOKE test_app FROM {role}'

  owner:
    type: nspacl
    grant: 'GRANT test_owner TO {role}'
    revoke: 'REVOKE test_owner FROM {role}'
``` 

This does work but as I am not sure how to do a correct inspect part for this the grants are set again on every run. Maybe there is a much more elegant solution?

My second "problem" ist, if a role gets dropped the objects of the role are reassigned to postgres user, is it possible to reassign the objects to another user?

Thanks,
Dennis
