### ISSUE TITLE
ldap2pg spits SQLASCII if postgres locale is C

### ISSUE THREAD

**Issue by guruguruguru** [dalibo/ldap2pg#334]
## ldap2pg.yml
``` yaml
verbosity: 0

postgres:
  # Scope the database where to purge objects when dropping roles. This is the
  # scope of grant on `__all__` databases.
  databases_query: [postgres, test , adddb01 ]
  blacklist: [postgres, powa, dbcheck, repmgr , 'test_*' , 'adddb01_*' ]
  # List of managed schema. This skip pg_toast, pg_temp1, etc. but not pg_catalog.
  schemas_query: |
    SELECT nspname FROM pg_catalog.pg_namespace
    WHERE nspname = 'pg_catalog' OR nspname NOT LIKE 'pg_%'
  # Return managed roles which can be dropped or revoked.
  managed_roles_query: |
    SELECT 'public'
    UNION
    SELECT DISTINCT role.rolname
    FROM pg_roles AS role
    LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
    LEFT OUTER JOIN pg_roles AS ldap_roles
      ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
    WHERE role.rolname IN ('ldap_roles')
        OR ldap_roles.oid IS NOT NULL
    ORDER BY 1;

  # Since readers/writer/owners groups are globals, we have a global
  # owners_query.
  owners_query: |
    SELECT DISTINCT role.rolname
    FROM pg_catalog.pg_roles AS role
    JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
    JOIN pg_catalog.pg_roles AS owners
      ON owners.rolname = 'owners' AND owners.oid = ms.roleid
    ORDER BY 1;

ldap:
  uri: ldaps://XXX.server.lan
  binddn: uid=system_postgres_auth,cn=oradba-grp-db-access,cn=oradba,ou=ampua
  password: XXX

sync_map:
# Now query LDAP to create roles and grant them privileges by parenting.

- roles: 
  - name: ldap_roles
  - name: ampua_test_owner
    options: NOINHERIT
    parent: ldap_roles
  - names: 
    - ampua_test_app
    - ampua_test_read
    parent: ldap_roles
  - name: ampua_adddb01_owner
    options: NOINHERIT
    parent: ldap_roles
  - names: 
    - ampua_adddb01_app
    - ampua_adddb01_read
    parent: ldap_roles


- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX))"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_test_owner
    - ampua_test_app
    - ldap_roles

- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX))"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_test_app
    - ldap_roles

- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX))"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_test_read
    - ldap_roles
# additional dbs
#

- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX)"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_adddb01_owner
    - ampua_adddb01_app
    - ldap_roles

- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX)"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_adddb01_app
    - ldap_roles

- ldap:
    base: ou=ampua
    filter: "(&(objectClass=organizationalPerson)(memberOf=XXX))"
  roles:
    name: '{uid}'
    options: LOGIN
    parent:
    - ampua_adddb01_read
    - ldap_roles
```

## Expectations

Works on CentOS7 with Version 5.0 (python2)
Does not work on CentOS8 with Version 5.4.1 (python3)

## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary><pre>
[ldap2pg.config        INFO] Starting ldap2pg 5.4.
[ldap2pg.config       DEBUG] Trying /etc/postgresql/ldap2pg.yml.
[ldap2pg.config        INFO] Using /etc/postgresql/ldap2pg.yml.
[ldap2pg.config       DEBUG] Read dry from argv.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read ldap:uri from YAML.
[ldap2pg.config       DEBUG] Read ldap:binddn from YAML.
[ldap2pg.config       DEBUG] Read ldap:password from YAML.
[ldap2pg.config       DEBUG] Read postgres:databases_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:owners_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:managed_roles_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:roles_blacklist_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:schemas_query from YAML.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __connect__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __create_on_schemas__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_delete_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_insert_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_references_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_trigger_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_truncate_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_types__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __delete_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __insert_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __references_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __temporary__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __trigger_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __truncate_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_schemas__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Setting up LDAP client.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/etc/ldap/ldap.conf'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/home/postgres/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: '/home/postgres/.ldaprc'
[ldap2pg.ldap         DEBUG] Read TLS_CACERT from env.
[ldap2pg.ldap         DEBUG] Read URI from YAML.
[ldap2pg.ldap         DEBUG] Read BINDDN from YAML.
[ldap2pg.ldap         DEBUG] Read PASSWORD from YAML.
[ldap2pg.ldap         DEBUG] Connecting to LDAP server XXX
[ldap2pg.ldap         DEBUG] Trying simple bind.
[ldap2pg.ldap         DEBUG] Doing: ldapwhoami -x -D uid=XXX -W
[ldap2pg.script        INFO] Running in real mode.
[ldap2pg.psql         DEBUG] Connecting to Postgres libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT array_agg(attrs.attname)
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_namespace AS nsp
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_class AS tables
[ldap2pg.psql         DEBUG]   ON tables.relnamespace = nsp.oid AND tables.relname = 'pg_authid'
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_attribute AS attrs
[ldap2pg.psql         DEBUG]   ON attrs.attrelid = tables.oid AND attrs.attname LIKE 'rol%'
[ldap2pg.psql         DEBUG] WHERE nsp.nspname = 'pg_catalog'
[ldap2pg.psql         DEBUG] ORDER BY 1
[ldap2pg.role         DEBUG] Postgres server supports role options BYPASSRLS, LOGIN, CREATEDB, CREATEROLE, INHERIT, REPLICATION, SUPERUSER.
[ldap2pg.manager       INFO] Inspecting roles in Postgres cluster...
[ldap2pg.psql         DEBUG] Using Postgres connection to libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT current_user, rolsuper
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_roles
[ldap2pg.psql         DEBUG] WHERE rolname = current_user;
[ldap2pg.psql         DEBUG] Using Postgres connection to libpq default.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   role.rolname, array_agg(members.rolname) AS members,
[ldap2pg.psql         DEBUG]   role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper,
[ldap2pg.psql         DEBUG]   pg_catalog.shobj_description(role.oid, 'pg_authid') as comment
[ldap2pg.psql         DEBUG] FROM
[ldap2pg.psql         DEBUG]   pg_catalog.pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
[ldap2pg.psql         DEBUG] GROUP BY role.rolname, role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper, comment
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Listing managed roles.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT 'public'
[ldap2pg.psql         DEBUG] UNION
[ldap2pg.psql         DEBUG] SELECT DISTINCT role.rolname
[ldap2pg.psql         DEBUG] FROM pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_roles AS ldap_roles
[ldap2pg.psql         DEBUG]   ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
[ldap2pg.psql         DEBUG] WHERE role.rolname IN ('ldap_roles')
[ldap2pg.psql         DEBUG]     OR ldap_roles.oid IS NOT NULL
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] May reuse role 'pg_read_all_settings'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_monitor'.
[ldap2pg.inspector    DEBUG] Ignoring role 'postgres'. Matches 'postgres'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_execute_server_program'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_read_server_files'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_stat_scan_tables'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_read_all_stats'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_signal_backend'.
[ldap2pg.inspector    DEBUG] May reuse role 'pg_write_server_files'.
[ldap2pg.manager      DEBUG] Postgres roles inspection done.
[ldap2pg.manager      DEBUG] Want role ldap_roles from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_test_owner from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_test_app from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_test_read from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_adddb01_owner from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_adddb01_app from YAML.
[ldap2pg.manager      DEBUG] Want role ampua_adddb01_read from YAML.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager      DEBUG] Want role noob in LDAP.
[ldap2pg.manager      DEBUG] Want role ratta in LDAP.
[ldap2pg.manager      DEBUG] Want role raven in LDAP.
[ldap2pg.manager      DEBUG] Want role cnjvwc in LDAP.
[ldap2pg.manager      DEBUG] Want role lyltef in LDAP.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager      DEBUG] Want role nahhef in LDAP.
[ldap2pg.manager      DEBUG] Want role odritd in LDAP.
[ldap2pg.manager      DEBUG] Want role egpvuf in LDAP.
[ldap2pg.manager      DEBUG] Want role nhriyf in LDAP.
[ldap2pg.manager      DEBUG] Want role oisqsg in LDAP.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 11 entries from LDAP.
[ldap2pg.manager      DEBUG] Want role fggvfb in LDAP.
[ldap2pg.manager      DEBUG] Want role qqkfec in LDAP.
[ldap2pg.manager      DEBUG] Want role mnjl in LDAP.
[ldap2pg.manager      DEBUG] Want role repd in LDAP.
[ldap2pg.manager      DEBUG] Want role zxjl in LDAP.
[ldap2pg.manager      DEBUG] Want role npqyb in LDAP.
[ldap2pg.manager      DEBUG] Want role zcakq in LDAP.
[ldap2pg.manager      DEBUG] Want role ftpgwe in LDAP.
[ldap2pg.manager      DEBUG] Want role mkahzd in LDAP.
[ldap2pg.manager      DEBUG] Want role xewqne in LDAP.
[ldap2pg.manager      DEBUG] Want role owgtsg in LDAP.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager       INFO] Querying LDAP ou=ampua... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D uid=XXX...
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager      DEBUG] LDAP inspection completed. Post processing.
[ldap2pg.psql         DEBUG] Using Postgres connection to libpq default.
[ldap2pg.psql         CHANG] Create noob.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/lib/python3.6/site-packages/ldap2pg/script.py", line 94, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/lib/python3.6/site-packages/ldap2pg/script.py", line 70, in wrapped_main
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/lib/python3.6/site-packages/ldap2pg/manager.py", line 250, in sync
[ldap2pg.script       ERROR]     databases=databases))
[ldap2pg.script       ERROR]   File "/usr/lib/python3.6/site-packages/ldap2pg/psql.py", line 104, in run_queries
[ldap2pg.script       ERROR]     sql = session.mogrify(*query.args)
[ldap2pg.script       ERROR]   File "/usr/lib/python3.6/site-packages/ldap2pg/psql.py", line 161, in mogrify
[ldap2pg.script       ERROR]     return sql.decode(self.conn.encoding)
[ldap2pg.script       ERROR] LookupError: unknown encoding: SQLASCII
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.

...
$
</pre></details>
