### ISSUE TITLE
How to alter role ldap_roles in the ldap2pg.yml script

### ISSUE THREAD

**Issue by HermanPool** [dalibo/ldap2pg#368]
I use enterprisedb postgres.
How can I alter the role ldap_roles in the ldap2pg.yml file?
After creating the role ldap_roles I want to alter the role with the statement:
alter role ldap_roles set edb_audit_statement to 'all'

I want to alter the role in the ldap2pg.yml file and not in a seperate sql file or script.

**Comment by bersace** [comment]
Hi @HermanPool , thanks for reaching.

There is nothing like custom sql as of now in ldap2pg, except for privileges.

There is a workaround through, but quite ugly, use a privilege. Something like :

``` yaml
privileges:
  edb_audit_statement:
    grant: ALTER ROLE {role} SET edb_audit_statement to 'all'

sync_map:
- grant:
    privilege: edb_audit_statement
    role: ldap_roles
```

YMMV.

This looks like #171.
