### ISSUE TITLE
cn.lower() raises AttributeError: 'str' object has no attribute 'lower()'

### ISSUE THREAD

**Issue by jeanpommier** [dalibo/ldap2pg#378]
Hi,
While the doc states that we can use lower() / upper() functions, it doesn't seem to work in my case.

I'm using the latest docker image.

## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>

``` yaml
#
#
#       L D A P 2 P G   S A M P L E   C O N F I G U R A T I O N
#
#
# This is a starting point configuration file for ldap2pg.yml. Including static
# roles, groups, privilege and LDAP query.
#
# This configuration assumes the following principles:
#
# - All LDAP users are grouped in `ldap_roles` group.
# - Read privileges are granted to `readers` group.
# - Write privileges are granted to `writers` group.
# - DDL privileges are granted to `owners` group.
# - We have one or more databases with public and maybe a schema.
# - Grants are not specific to a schema. Once you're writer in a database, you
#   are writer to all schemas in it.
#
# The LDAP directory content is described in fixtures/openldap-data.ldif
#
# Adapt to your needs! See also full documentation on how to configure ldap2pg
# at https://ldap2pg.readthedocs.io/en/latest/config/.
#
# Don't hesitate to suggest improvements for this starting configuration at
# https://github.com/dalibo/ldap2pg/issues/new . Thanks for your contribution !
#

#
# File format version. Allows ldap2pg to check whether the file is supported.
#
#version: 5
# Colorization. env var: COLOR=<anything>
color: yes
#
# # Verbose messages. Includes SQL and LDAP queries. env var: VERBOSITY
# verbosity: 5
#
# # Dry mode. env var: DRY=<anything>
# dry: yes

#
#       0.   LDAP   CONFIG
#
ldap:
  uri: ldap://192.168.1.70:3389
  binddn: cn=admin,dc=georchestra,dc=org
  password: super_secret_password

#
#       1.   P O S T G R E S   I N S P E C T I O N
#
#  See https://ldap2pg.readthedocs.io/en/latest/postgres/
#

postgres:
  #dsn: "host=192.168.1.70 port=5432 user=georchestra dbname=georchestra"
  dsn: postgres://georchestra:super_secret_password@192.168.1.70:5432/georchestra
  databases_query: |
    SELECT datname
    FROM pg_catalog.pg_database
    WHERE datallowconn IS TRUE
    AND datname NOT IN ('postgres','template1', 'template_postgis');

  # List of role names which can be dropped from cluster. Privileges on these
  # roles can be revoked.
  managed_roles_query: |
    SELECT 'public'
    UNION
    SELECT DISTINCT role.rolname
    FROM pg_roles AS role
    LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
    LEFT OUTER JOIN pg_roles AS ldap_roles
      ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
    WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
        OR ldap_roles.oid IS NOT NULL
    ORDER BY 1;

  # List of object owners that requires default privileges configuration. Since
  # readers/writer/owners groups are globals to cluster, we have a global
  # owners_query.
  owners_query: |
    SELECT DISTINCT role.rolname
    FROM pg_catalog.pg_roles AS role
    JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
    JOIN pg_catalog.pg_roles AS owners
      ON owners.rolname = 'owners' AND owners.oid = ms.roleid
    ORDER BY 1;

  # Exclude information_schema, pg_catalog, pg_toast, and other system schemas
  # from privilege management.
  schemas_query: |
    SELECT
      nspname,
      array_agg(owner.rolname) FILTER (WHERE owner.rolname IS NOT NULL)
    FROM pg_catalog.pg_namespace
    LEFT OUTER JOIN pg_catalog.pg_roles AS owners_group
      ON owners_group.rolname = 'owners_' || nspname
    LEFT OUTER JOIN pg_catalog.pg_auth_members AS ms ON ms.roleid = owners_group.oid
    LEFT OUTER JOIN pg_catalog.pg_roles AS owner ON owner.oid = ms.member
    WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
    GROUP BY 1


#
#       2.   P R I V I L E G E S   D E F I N I T I O N
#
# See https://ldap2pg.readthedocs.io/en/latest/privileges/. Privileges wrapped
# in double underscores are well-known privileges built-in ldap2pg. See
# https://ldap2pg.readthedocs.io/en/latest/wellknown/ for a documentation of
# each of them.
#

privileges:
  # Define `ro` privilege group with read-only grants
  ro:
  - __connect__
  - __select_on_tables__
  - __select_on_sequences__
  - __usage_on_schemas__
  - __usage_on_types__

  # `rw` privilege group lists write-only grants
  rw:
  - __temporary__
  - __all_on_tables__
  - __all_on_sequences__

  # `ddl` privilege group lists DDL only grants.
  ddl:
  - __create_on_schemas__


#
#       3.   S Y N C H R O N I S A T I O N   M A P
#
# This list contains rules to declare roles and grants. Each role or grant rule
# can be templated with attributes from LDAP entries returned by a search
# query.
#
# Any role found in cluster and not generated by sync_map will be dropped. Any
# grant found in cluster and not generated by sync_map will be revoked.
#

sync_map:
- description: "Setup static roles and grants."
  roles:
  - names:
    - ldap_roles
    - readers
    options: NOLOGIN
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN

  grant:
  - privilege: ro
    role: readers
    schemas: __all__
  - privilege: rw
    role: writers
    schema: __all__
  - privilege: ddl
    role: owners
    schema: __all__

- description: "Query LDAP to create dynamic roles."
  ldap:
    base: ou=roles,dc=georchestra,dc=org
    filter: "(cn=PGSQL_*)"
  role:
    # LDAP attribute member is a Distinguished Name. Use CN component of the
    # member value.
    name: '{cn.lower()}'
    options: NOLOGIN
    parent:
    - ldap_roles
    comment: "From LDAP group {dn}"

- description: "Query LDAP to create superusers."
  ldap:
    base: dc=georchestra,dc=org
    filter: "(memberOf=cn=CKAN_SYSADMIN,ou=roles,dc=georchestra,dc=org)"
  role:
    # LDAP attribute member is a Distinguished Name. Use CN component of the
    # member value.
    name: '{uid}'
    options: LOGIN SUPERUSER
    parent:
    - ldap_roles
    - owners
    comment: "From LDAP group {dn}"


- description: "Query LDAP to create writers."
  ldap:
    base: dc=georchestra,dc=org
    filter: "(memberOf=cn=CKAN_ADMIN,ou=roles,dc=georchestra,dc=org)"
    on_unexpected_dn: warn
  role:
    name: '{uid}'
    options: LOGIN
    parent:
    - ldap_roles
    - writers
    comment: 'From LDAP groupe {dn}'

- description: "Query LDAP to create readers."
  ldap:
    base: dc=georchestra,dc=org
    filter: "(memberOf=cn=CKAN_EDITOR,ou=roles,dc=georchestra,dc=org)"
  role:
    name: '{uid}'
    options: LOGIN
    parent:
    - ldap_roles
    - readers

```
</details>

## Expectations

- What you expected from ldap2pg ?
I would expect the roles extracted from the LDAP query to be lower, as per {cn.lower()}
- What ldap2pg did wrong ?
It raises an error
```
AttributeError: 'str' object has no attribute 'lower()'
```

I'm using the dalibo/ldap2pg docker image
## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary>

``` console
$ docker run --rm --volume ${PWD}:/workspace dalibo/ldap2pg:latest --verbose --dry
[ldap2pg.config        INFO] Starting ldap2pg 5.5.
[ldap2pg.config       DEBUG] Trying ./ldap2pg.yml.
[ldap2pg.config        INFO] Using /workspace/ldap2pg.yml
....
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT datname
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_database
[ldap2pg.psql         DEBUG] WHERE datallowconn IS TRUE
[ldap2pg.psql         DEBUG] AND datname NOT IN ('postgres','template1', 'template_postgis');
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   role.rolname, array_agg(members.rolname) AS members,
[ldap2pg.psql         DEBUG]   role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper,
[ldap2pg.psql         DEBUG]   pg_catalog.shobj_description(role.oid, 'pg_authid') as comment
[ldap2pg.psql         DEBUG] FROM
[ldap2pg.psql         DEBUG]   pg_catalog.pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
[ldap2pg.psql         DEBUG] GROUP BY role.rolname, role.rolbypassrls, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, role.rolreplication, role.rolsuper, comment
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Listing managed roles.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT 'public'
[ldap2pg.psql         DEBUG] UNION
[ldap2pg.psql         DEBUG] SELECT DISTINCT role.rolname
[ldap2pg.psql         DEBUG] FROM pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_roles AS ldap_roles
[ldap2pg.psql         DEBUG]   ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
[ldap2pg.psql         DEBUG] WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
[ldap2pg.psql         DEBUG]     OR ldap_roles.oid IS NOT NULL
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_write_server_files'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_all_settings'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_monitor'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'georchestra'. Matches 'georchestra'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_stat_scan_tables'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_all_stats'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_execute_server_program'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_signal_backend'. Matches 'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_server_files'. Matches 'pg_*'.
[ldap2pg.manager      DEBUG] Postgres roles inspection done.
[ldap2pg.manager       INFO] Setup static roles and grants.
[ldap2pg.manager      DEBUG] Want role ldap_roles from YAML.
[ldap2pg.manager      DEBUG] Want role readers from YAML.
[ldap2pg.manager      DEBUG] Want role writers from YAML.
[ldap2pg.manager      DEBUG] Want role owners from YAML.
[ldap2pg.manager      DEBUG] Want GRANT ro on __ALL_DATABASES__.* for * to readers (full) from YAML.
[ldap2pg.manager      DEBUG] Want GRANT rw on __ALL_DATABASES__.* for * to writers (full) from YAML.
[ldap2pg.manager      DEBUG] Want GRANT ddl on __ALL_DATABASES__.* for * to owners (full) from YAML.
[ldap2pg.manager       INFO] Query LDAP to create dynamic roles.
[ldap2pg.manager       INFO] Querying LDAP ou=roles,dc=georchestra,... (cn=PGSQL_*)...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D cn=admin,dc=georchestra,dc=org -W -b ou=roles,dc=georchestra,dc=org -s sub '(cn=PGSQL_*)' cn
[ldap2pg.manager      DEBUG] Got 2 entries from LDAP.
[ldap2pg.manager      WARNI] Missing 'member' from cn=PGSQL_STATSOFFICE_OWNER,ou=roles,dc=georchestra,dc=org. Considering it as an empty list.
[ldap2pg.manager      WARNI] Missing 'member' from cn=PGSQL_STATSOFFICE_READER,ou=roles,dc=georchestra,dc=org. Considering it as an empty list.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 94, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/script.py", line 70, in wrapped_main
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/manager.py", line 292, in sync
[ldap2pg.script       ERROR]     ldaproles, ldapacl = self.inspect_ldap(syncmap)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/manager.py", line 179, in inspect_ldap
[ldap2pg.script       ERROR]     rule, ldaproles, vars_, log_source)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/manager.py", line 226, in apply_role_rule
[ldap2pg.script       ERROR]     for role in rule.generate(vars_):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/role.py", line 396, in generate
[ldap2pg.script       ERROR]     for (i, name), (comment, repeated) in zip(enumerate(names), comments):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/format.py", line 251, in expand
[ldap2pg.script       ERROR]     for string in spec.expand(vars_):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.7/dist-packages/ldap2pg/format.py", line 98, in expand
[ldap2pg.script       ERROR]     yield self.spec.format(**combination)
[ldap2pg.script       ERROR] AttributeError: 'str' object has no attribute 'lower()'
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log
```

</details>
