### ISSUE TITLE
How to use API? value = environ[env] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by meegoSVK** [dalibo/ldap2pg#431]
Hi. I want to use this python API, but I am not able to make it work. I always get TypeError. I wanted to try it example on your site, but it is not working. Also the yaml files I am using are not working with the API.

This yaml file is working when I execute it via
`ldap2pg -c test.yaml`

<details><summary>working code</summary>

```
(.venv) meego@mytreehost$ ldap2pg -c test.yaml 
Starting ldap2pg 5.8.
Using /home/meego/git_projects/project1/test.yaml.
Connecting to LDAP server ldaps://ad.mytreecompany.org:636.
Trying simple bind.
Running in dry mode. Postgres will be untouched.
Inspecting roles in Postgres cluster...
Querying LDAP OU=PGSQL,OU=TB_Groups,OU... (cn=sgrp_pgs...
Sub-querying LDAP CN=User1,OU=TREE...
Missing 'member' from CN=User1,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User2,OU=TREE...
Missing 'member' from CN=User2,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=meego,OU=TREE...
Missing 'member' from CN=meego,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User3,OU=TREE...
Missing 'member' from CN=User3,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User4,OU=TREE...
Missing 'member' from CN=User4,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User5,OU=TREE...
Missing 'member' from CN=User5,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User6,OU=TREE...
Missing 'member' from CN=User6,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User7,OU=TREE...
Missing 'member' from CN=User7,HERE_IS_THE_TREE. Considering it as an empty list.
Sub-querying LDAP CN=User8,OU=TREE...
Missing 'member' from CN=User8,HERE_IS_THE_TREE. Considering it as an empty list.
Would create meego.
Would create User1.
Would rename User6 to User6.
Would rename User4 to User4.
Would rename User2 to User2.
Would rename User8 to User8.
Would rename User7 to User7.
Would rename User5 to User5.
Role User6 already exists in cluster. Reusing.
Would update comment on User6.
Role User4 already exists in cluster. Reusing.
Role User2 already exists in cluster. Reusing.
Role User8 already exists in cluster. Reusing.
Would update comment on User8.
Role User7 already exists in cluster. Reusing.
Would update comment on User7.
Role User5 already exists in cluster. Reusing.
Would update comment on User5.
Role User3 already exists in cluster. Reusing.
Would update options of User3.
Would update comment on User3.
Role ldap_admins already exists in cluster. Reusing.
Would add missing ldap_admins members.
Inspecting GRANTs in Postgres cluster...
In dry mode, some owners aren't created, their default privileges can't be determined.
Would grant set_audit on postgres to User7.
Would grant set_audit on postgres to User8.
Would grant set_audit on postgres to User6.
Would grant set_audit on postgres to User5.
Would grant set_audit on postgres to User4.
Would grant set_audit on postgres to User3.
Would grant set_audit on postgres to meego.
Would grant set_audit on postgres to User2.
Would grant set_audit on postgres to User1.
Generated 24 querie(s).
Comparison complete.
(.venv) meego@mytreehost$ 
```

</details>

<details><summary>ldap2pg.yaml</summary>

```yaml
ldap:
  binddn: CN=veryspecialuser,OU=rest_of_tree
  password: VerySecretPa4$word
  uri: ldaps://ad.mytreecompany.org:636
postgres:
  databases_query:
  - postgres
  dsn: postgres://meego:VerySecretPa4@mytreehost:5432/postgres
  managed_roles_query: SELECT DISTINCT role.rolname FROM pg_roles AS role LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid LEFT OUTER JOIN pg_roles  AS ldap_roles   ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners') OR ldap_roles.oid  IS NOT NULL ORDER BY 1
  owners_query: SELECT DISTINCT role.rolname FROM pg_catalog.pg_roles AS role JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid JOIN pg_catalog.pg_roles AS owners   ON owners.rolname = 'owners' AND owners.oid = ms.roleid ORDER  BY 1
  schemas_query: SELECT nspname FROM pg_catalog.pg_namespace WHERE nspname = 'pg_catalog' OR nspname NOT LIKE 'pg_%'
privileges:
  set_audit:
    grant: ALTER ROLE {role} SET pgaudit.role to 'audit_profile'
    inspect: select cfg, usename from (select usename, unnest(useconfig) as cfg from pg_user) as slct where cfg like '%pgaudit%';
    type: datacl
sync_map:
- roles:
  - comment: Group created for LDAP synchronization.
    names:
    - ldap_admins
    options: NOLOGIN
- grant:
    privilege: set_audit
    role: '{member.cn.lower()}'
  ldapsearch:
    allow_missing_attributes: []
    base: OU=PGSQL,OU=rest_of_tree
    filter: (cn=spesl_group)
  role:
    comment: Superuser account from AD - User {member.displayName}
    name: '{member.cn.lower()}'
    on_unexpected_dn: warn
    options: LOGIN SUPERUSER CREATEROLE CREATEDB
    parent:
    - ldap_admins
```

</details>

When I try to make it run over API, I get error:

```
>>> from textwrap import dedent
>>> from ldap2pg import synchronize, UserError
>>> try:
...   synchronize(dedent("""\
...   ldap:
...     binddn: CN=veryspecialuser,OU=rest_of_tree
...     password: VerySecretPa4$word
...     uri: ldaps://ad.mytreecompany.org:636
...   postgres:
...     databases_query:
...     - postgres
...     dsn: postgres://meego:VerySecretPa4@mytreehost:5432/postgres
...     managed_roles_query: SELECT DISTINCT role.rolname FROM pg_roles AS role LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid LEFT OUTER JOIN pg_roles  AS ldap_roles   ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners') OR ldap_roles.oid  IS NOT NULL ORDER BY 1
...     owners_query: SELECT DISTINCT role.rolname FROM pg_catalog.pg_roles AS role JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid JOIN pg_catalog.pg_roles AS owners   ON owners.rolname = 'owners' AND owners.oid = ms.roleid ORDER  BY 1
...     schemas_query: SELECT nspname FROM pg_catalog.pg_namespace WHERE nspname = 'pg_catalog' OR nspname NOT LIKE 'pg_%'
...   privileges:
...     set_audit:
...       grant: ALTER ROLE {role} SET pgaudit.role to 'audit_profile'
...       inspect: select cfg, usename from (select usename, unnest(useconfig) as cfg from pg_user) as slct where cfg like '%pgaudit%';
...       type: datacl
...   sync_map:
...   - roles:
...     - comment: Group created for LDAP synchronization.
...       names:
...       - ldap_admins
...       options: NOLOGIN
...   - grant:
...       privilege: set_audit
...       role: '{member.cn.lower()}'
...     ldapsearch:
...       allow_missing_attributes: []
...       base: OU=PGSQL,OU=rest_of_tree
...       filter: (cn=spesl_group)
...     role:
...       comment: Superuser account from AD - User {member.displayName}
...       name: '{member.cn.lower()}'
...       on_unexpected_dn: warn
...       options: LOGIN SUPERUSER CREATEROLE CREATEDB
...       parent:
...       - ldap_admins
...   """))
... except UserError as e:
...   logger.error("%s", e)
... 
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "/home/meego/git_projects/project1/.venv/lib64/python3.6/site-packages/ldap2pg/script.py", line 88, in synchronize
    config = init_config(config, environ, argv)
  File "/home/meego/git_projects/project1/.venv/lib64/python3.6/site-packages/ldap2pg/script.py", line 66, in init_config
    config_obj.merge(config, environ, args)
  File "/home/meego/git_projects/project1/.venv/lib64/python3.6/site-packages/ldap2pg/config.py", line 599, in merge
    args=args,
  File "/home/meego/git_projects/project1/.venv/lib64/python3.6/site-packages/ldap2pg/config.py", line 303, in process
    value = callable_(*args)
  File "/home/meego/git_projects/project1/.venv/lib64/python3.6/site-packages/ldap2pg/config.py", line 254, in process_env
    value = environ[env]
TypeError: 'NoneType' object is not subscriptable
>>> 
```

ldap2pg version, packages and OS

```
(.venv) meego@mytreehos$ ldap2pg --version
ldap2pg 5.8
psycopg2 2.9.5 (dt dec pq3 ext lo64) libpq 15.0
python-ldap 3.4.3
Python 3.6.8 (default, Aug 13 2020, 07:46:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
(.venv) meego@mytreehos$ pip freeze
ldap2pg==5.8
ldap3==2.9.1
psycopg2-binary==2.9.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-ldap==3.4.3
PyYAML==6.0
(.venv) meego@mytreehos$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
(.venv) meego@mytreehos$ 
```

Could you please help me to understand how that API should work?
Thank you very much.

Sincerely meego
