### ISSUE TITLE
Error of ldap2pg.script on postgreSQL 15

### ISSUE THREAD

**Issue by LexaNz** [dalibo/ldap2pg#438]
Salut Dalibo !

We use your ldap2pg docker image to apply permission/access from AD
It's an ansible deployment so excuse variables in conf files

For now I observed the error on our new instance PostGIS 15.1 3.3 - docker file below

``` console

FROM postgis/postgis:15-3.3

RUN apt update
RUN apt install -y wget lsb-release wget software-properties-common apt-transport-https
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c -s)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
RUN apt update
RUN apt install -y postgresql-15-ogr-fdw
RUN apt autoremove
RUN apt clean
```

Here how ldap2g container is launched via Ansible
```yaml
- name: Deploy Ldap2PG container and sync permissions via LDAP
  community.docker.docker_container:
    name: ldap2pg
    image: dalibo/ldap2pg
    command: --verbose --real
    state: started
    pull: yes
    volumes:
      - "{{ psql_containers_path }}/ldap2pg/:/workspace/"
      - "{{ psql_containers_path }}/ldap_CA.crt:/etc/ssl/certs/ldap_CA.crt"
      - "{{ psql_containers_path }}/ldap.conf:/etc/ldap/ldap.conf"
    env:
      TZ: "Pacific/Auckland"
      PGUSER: "postgres"
      PGHOSTADDR: "{{ psql_dk_running_ip }}"
      PGPORT: "5432"
      LDAPURI: "ldaps://{{ ldap_server_name_psql }}"
      LDAPBINDDN: "cn={{ ldap_search_user_psql }},{{ ldap_binddn_psql }},{{ ldap_suffix_psql }}"
      LDAPPASSWORD: "{{ ldap_search_password_psql }}"
```

## ldap2pg.yml

``` yaml
postgres:
# List of role names which can be dropped from cluster. Privileges on these
  # roles can be revoked.
  managed_roles_query: |
    SELECT 'public'
    UNION
    SELECT DISTINCT role.rolname
    FROM pg_roles AS role
    LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
    LEFT OUTER JOIN pg_roles AS ldap_roles
      ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
    WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners', 'company_dba')
        OR ldap_roles.oid IS NOT NULL
    ORDER BY 1;

  # List of object owners that requires default privileges configuration. Since
  # readers/writer/owners groups are globals to cluster, we have a global
  # owners_query.
  owners_query: |
    SELECT DISTINCT role.rolname
    FROM pg_catalog.pg_roles AS role
    JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
    JOIN pg_catalog.pg_roles AS owners
      ON owners.rolname = 'owners' AND owners.oid = ms.roleid
    ORDER BY 1;

  # Exclude information_schema, pg_catalog, pg_toast, and other system schemas
  # from privilege management.
  schemas_query: |
    SELECT nspname FROM pg_catalog.pg_namespace
    WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
    ORDER BY 1;


#
#       2.   P R I V I L E G E S   D E F I N I T I O N
#
# See https://ldap2pg.readthedocs.io/en/latest/privileges/. Privileges wrapped
# in double underscores are well-known privileges built-in ldap2pg. See
# https://ldap2pg.readthedocs.io/en/latest/wellknown/ for a documentation of
# each of them.
#

privileges:
  # Define `ro` privilege group with read-only grants
  ro:
  - __connect__
  - __select_on_tables__
  - __select_on_sequences__
  - __usage_on_schemas__
  - __usage_on_types__

  # `rw` privilege group lists write-only grants
  rw:
  - __temporary__
  - __all_on_tables__
  - __all_on_sequences__

  # `ddl` privilege group lists DDL only grants.
  ddl:
  - __create_on_schemas__

sync_map:
 - description: "Setup static roles and grants."
  roles:
  - names:
    - ldap_roles
    - readers
    options: NOLOGIN
    comment: Ansible managed Role
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
    comment: Ansible managed Role
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN
    comment: Ansible managed Role
    # Grant Superuser to company_dba
  - name: company_dba
    options: NOLOGIN SUPERUSER
    comment: Ansible managed Role (DBA)

  grant:
  - privilege: ro
    role: readers
    schemas: __all__
  - privilege: rw
    role: writers
    schema: __all__
  - privilege: ddl
    role: owners
    schema: __all__


# Query Superusers - Will be owner on the instance and can use company_dba role
# ONLY T1 Accounts allowed here !
- description: "Query LDAP for superusers."
  ldap:
    base: {{ ldap_suffix_psql }}
    scope: sub
    filter: >
      (&
        (objectClass=User)
        (memberOf:1.2.840.113556.1.4.1941:=cn={{ psql_admin_group }},{{ ldap_filter_psql_admin }},{{ ldap_suffix_psql }})
      )
  role:
    name: '{sAMAccountName}'
    options: LOGIN
    parent:
    - ldap_roles
    - owners
    - company_dba
    comment: 'AD managed Role (ADMIN) - {{ psql_admin_group }}'


# Query Writers. Can write on All Databases.
- description: "Query LDAP to create writers."
  ldap:
    base: {{ ldap_suffix_psql }}
    scope: sub
    filter: >
      (&
        (objectClass=User)
        (memberOf:1.2.840.113556.1.4.1941:=cn={{ psql_writer_group }},{{ ldap_filter_psql_users }},{{ ldap_suffix_psql }})
      )
  role:
    name: '{sAMAccountName}'
    options: LOGIN
    parent:
    - ldap_roles
    - writers
    comment: 'AD managed Role - {{ psql_writer_group }}'

# Query Writers. Can read on All Databases.
- description: "Query LDAP to create readers."
  ldap:
    base: {{ ldap_suffix_psql }}
    scope: sub
    filter: >
      (&
        (objectClass=User)
        (memberOf:1.2.840.113556.1.4.1941:=cn={{ psql_reader_group }},{{ ldap_filter_psql_users }},{{ ldap_suffix_psql }})
      )
  role:
    name: '{sAMAccountName}'
    options: LOGIN
    parent:
    - ldap_roles
    - readers
    comment: 'AD managed Role - {{ psql_reader_group }}'

# Query Access only users. Can only LOGIN on instance
- description: "Query LDAP for access only users."
  ldap:
    base: {{ ldap_suffix_psql }}
    scope: sub
    filter: >
      (&
        (objectClass=User)
        (memberOf:1.2.840.113556.1.4.1941:=cn={{ psql_access_group }},{{ ldap_filter_psql_users }},{{ ldap_suffix_psql }})
      )
  role:
    name: '{sAMAccountName}'
    options: LOGIN
    parent:
    - ldap_roles
    comment: 'AD managed Role - {{ psql_access_group }}'
```

## Expectations

- What you expected from ldap2pg ?

ldap2pg.script should not returns errors

- What ldap2pg did wrong ?

Roles are granted correctly so except the python error I don't see any problem for now 

## Verbose output of ldap2pg execution

Head log cut, but no error for create role and GRANT
Instance is usable/accessible by AD users
No error in postgresql logs.

``` console
[ldap2pg.psql         DEBUG] CREATE ROLE "writers" WITH NOBYPASSRLS NOLOGIN NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOSUPERUSER;
[ldap2pg.psql         DEBUG] COMMENT ON ROLE "writers" IS 'Ansible managed Role';
[ldap2pg.psql         CHANG] Add writers members.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] GRANT "writers" TO "owners";
[ldap2pg.psql         CHANG] Create readers.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] CREATE ROLE "readers" WITH NOBYPASSRLS NOLOGIN NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOSUPERUSER;
[ldap2pg.psql         DEBUG] COMMENT ON ROLE "readers" IS 'Ansible managed Role';
[ldap2pg.psql         CHANG] Add readers members.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] GRANT "readers" TO "writers";
[ldap2pg.manager       INFO] Inspecting GRANTs in Postgres cluster...
[ldap2pg.inspector    DEBUG] Inspecting schemas in template1
[ldap2pg.psql         DEBUG] Opening connection to template1.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT nspname FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Found schemas public in template1.
[ldap2pg.inspector    DEBUG] Globally inspecting owners...
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT DISTINCT role.rolname
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_roles AS role
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_auth_members AS ms ON ms.member = role.oid
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_roles AS owners
[ldap2pg.psql         DEBUG]   ON owners.rolname = 'owners' AND owners.oid = ms.roleid
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Inspecting schemas in template_postgis
[ldap2pg.psql         DEBUG] Opening connection to template_postgis.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT nspname FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Found schemas public, tiger, tiger_data, topology in template_postgis.
[ldap2pg.inspector    DEBUG] Inspecting schemas in postgres
[ldap2pg.psql         DEBUG] Opening connection to postgres.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT nspname FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Found schemas public, tiger, tiger_data, topology in postgres.
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __connect__ in template1.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datname = current_database()
[ldap2pg.psql         DEBUG]   UNION
[ldap2pg.psql         DEBUG]   SELECT q.*
[ldap2pg.psql         DEBUG]   FROM (VALUES (0, 'CONNECT'), (0, 'TEMPORARY')) AS q
[ldap2pg.psql         DEBUG]   CROSS JOIN pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datacl IS NULL AND datname = current_database()
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   NULL as namespace,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public')
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE grantee = 0 OR rolname IS NOT NULL
[ldap2pg.inspector    DEBUG] Took 0:00:00.001697.
[ldap2pg.inspector    DEBUG] Found GRANT __connect__ on template1.* for * to public (full).
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __connect__ in template_postgis.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datname = current_database()
[ldap2pg.psql         DEBUG]   UNION
[ldap2pg.psql         DEBUG]   SELECT q.*
[ldap2pg.psql         DEBUG]   FROM (VALUES (0, 'CONNECT'), (0, 'TEMPORARY')) AS q
[ldap2pg.psql         DEBUG]   CROSS JOIN pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datacl IS NULL AND datname = current_database()
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   NULL as namespace,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public')
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE grantee = 0 OR rolname IS NOT NULL
[ldap2pg.inspector    DEBUG] Took 0:00:00.001685.
[ldap2pg.inspector    DEBUG] Found GRANT __connect__ on template_postgis.* for * to public (full).
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __connect__ in postgres.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(datacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datname = current_database()
[ldap2pg.psql         DEBUG]   UNION
[ldap2pg.psql         DEBUG]   SELECT q.*
[ldap2pg.psql         DEBUG]   FROM (VALUES (0, 'CONNECT'), (0, 'TEMPORARY')) AS q
[ldap2pg.psql         DEBUG]   CROSS JOIN pg_catalog.pg_database
[ldap2pg.psql         DEBUG]   WHERE datacl IS NULL AND datname = current_database()
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   NULL as namespace,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public')
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE grantee = 0 OR rolname IS NOT NULL
[ldap2pg.inspector    DEBUG] Took 0:00:00.001510.
[ldap2pg.inspector    DEBUG] Found GRANT __connect__ on postgres.* for * to public (full).
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __create_on_schemas__ in template1.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     nspname,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   nspname,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public') AS rolname
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE (grantee = 0 OR rolname IS NOT NULL)
[ldap2pg.psql         DEBUG]   AND nspname NOT LIKE 'pg\_%temp\_%'
[ldap2pg.psql         DEBUG]   AND nspname <> 'pg_toast'
[ldap2pg.psql         DEBUG] ORDER BY 1, 2
[ldap2pg.inspector    DEBUG] Took 0:00:00.000522.
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __create_on_schemas__ in template_postgis.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     nspname,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   nspname,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public') AS rolname
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE (grantee = 0 OR rolname IS NOT NULL)
[ldap2pg.psql         DEBUG]   AND nspname NOT LIKE 'pg\_%temp\_%'
[ldap2pg.psql         DEBUG]   AND nspname <> 'pg_toast'
[ldap2pg.psql         DEBUG] ORDER BY 1, 2
[ldap2pg.inspector    DEBUG] Took 0:00:00.000571.
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __create_on_schemas__ in postgres.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     nspname,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(nspacl)).privilege_type AS priv
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_namespace
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   grants.priv AS key,
[ldap2pg.psql         DEBUG]   nspname,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public') AS rolname
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE (grantee = 0 OR rolname IS NOT NULL)
[ldap2pg.psql         DEBUG]   AND nspname NOT LIKE 'pg\_%temp\_%'
[ldap2pg.psql         DEBUG]   AND nspname <> 'pg_toast'
[ldap2pg.psql         DEBUG] ORDER BY 1, 2
[ldap2pg.inspector    DEBUG] Took 0:00:00.000676.
[ldap2pg.inspector    DEBUG] Searching GRANTs of privilege __default_delete_on_tables__ in template1.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] WITH
[ldap2pg.psql         DEBUG] grants AS (
[ldap2pg.psql         DEBUG]   SELECT
[ldap2pg.psql         DEBUG]     defaclnamespace,
[ldap2pg.psql         DEBUG]     defaclrole,
[ldap2pg.psql         DEBUG]     (aclexplode(defaclacl)).grantee AS grantee,
[ldap2pg.psql         DEBUG]     (aclexplode(defaclacl)).privilege_type AS priv,
[ldap2pg.psql         DEBUG]     defaclobjtype AS objtype
[ldap2pg.psql         DEBUG]   FROM pg_catalog.pg_default_acl
[ldap2pg.psql         DEBUG] )
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   priv || '_on_' || objtype AS key,
[ldap2pg.psql         DEBUG]   nspname,
[ldap2pg.psql         DEBUG]   COALESCE(rolname, 'public') AS rolname,
[ldap2pg.psql         DEBUG]   TRUE AS full,
[ldap2pg.psql         DEBUG]   pg_catalog.pg_get_userbyid(defaclrole) AS owner
[ldap2pg.psql         DEBUG] FROM grants
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_namespace nsp ON nsp.oid = defaclnamespace
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_catalog.pg_roles AS rol ON grants.grantee = rol.oid
[ldap2pg.psql         DEBUG] WHERE (grantee = 0 OR rolname IS NOT NULL)
[ldap2pg.psql         DEBUG]   AND nspname NOT LIKE 'pg\_%temp\_%'
[ldap2pg.psql         DEBUG]   AND nspname <> 'pg_toast'
[ldap2pg.psql         DEBUG] -- ORDER BY 1, 2, 3, 5
[ldap2pg.psql         DEBUG] Closing connection to libpq default.
[ldap2pg.psql         DEBUG] Closing connection to template1.
[ldap2pg.psql         DEBUG] Closing connection to template_postgis.
[ldap2pg.psql         DEBUG] Closing connection to postgres.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/script.py", line 37, in main
[ldap2pg.script       ERROR]     exit(synchronize(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/script.py", line 133, in synchronize
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/manager.py", line 331, in sync
[ldap2pg.script       ERROR]     pgacl = self.inspector.fetch_grants(schemas, pgmanagedroles)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 266, in fetch_grants
[ldap2pg.script       ERROR]     rows = self.fetch_shared_query(
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 292, in fetch_shared_query
[ldap2pg.script       ERROR]     rows = list(conn.query(None, self.shared_queries[name]))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/psql.py", line 122, in query
[ldap2pg.script       ERROR]     cur.execute(sql, *args)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/psql.py", line 168, in execute
[ldap2pg.script       ERROR]     return super(FactoryCursor, self).execute(query, *a, **kw)
[ldap2pg.script       ERROR] psycopg2.errors.AmbiguousFunction: operator is not unique: text || "char"
[ldap2pg.script       ERROR] LINE 12:   priv || '_on_' || objtype AS key,
[ldap2pg.script       ERROR]                           ^
[ldap2pg.script       ERROR] HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

</details>
