### ISSUE TITLE
Access to different database groups for different LDAP groups in same cluster

### ISSUE THREAD

**Issue by TezkaRabota** [dalibo/ldap2pg#441]
Hi,

I have following problem: I have two AD groups: groupA and groupB. I have my postgresql cluster with some databases which are named db1_something and some which are named db2_something. I want to allow access for users from groupA to databases named db1_something and for users from groupB to databases named db2_something. How can I achieve this? 

Regards, Domen

**Comment by bersace** [comment]
Hi @TezkaRabota , thanks for reaching.

Use `__connect__` privilege.

``` yaml
privileges:
  access: [__connect__]

sync_map:
  - role:
   -  names: [groupA, groupB]
      options: NOLOGIN
    grant:
    - privilege: access
      role: groupA
      database: db1_something
    - privilege: access
      role: groupB
      database: db2_something
```

YMMV
