### ISSUE TITLE
ldap2pg.script: Unknown parent role pg_read_all_data

### ISSUE THREAD

**Issue by ChuvashovIvan** [dalibo/ldap2pg#484]
Hello.
I usage version ldap2pg 5.9 and want in config file ldap2pg.conf to use default roles in PG (pg_read_all_data/pg_write_all_data)
Code from me script ldap2pg.conf is presented low
```
postgres:
  blacklist:
    - postgres
    - pg_*
    
sync_map:
- ldap:
    base: <base>
  role:
    name: '{uid}'
    options: LOGIN
    parent:
      - pg_read_all_data
```
But ldap2pg return me error
`CRITICAL:  ldap2pg.script: Unknown parent role pg_read_all_data`
I know why return error but I don't understand how fix the error. Who is describe ldap2pg.conf to using default roles of PG?
