### ISSUE TITLE
Add role_match to grant rule

### ISSUE THREAD

**Issue by bersace** [dalibo/ldap2pg#54]
Add a simple conditionnal againts role name to grant rule.

``` yaml
- grant:
    role_attribute: cn
    role_match: '*_R'
    acl: ro
```
