### ISSUE TITLE
Complex AD configuration V6.0

### ISSUE THREAD

**Issue by zemanekj** [dalibo/ldap2pg#587]
Hello,

I've been playing with ldap2pg in the lab for the past few days, trying to simulate a situation where I have multiple PostgreSQL instances in the organization and would like to be able to configure them individually in Active Directory (AD).

For this purpose, I created OU=Postgres,DC=lab,DC=local. Within this OU, I have OUs for each instance:

OU=postgre1.lab.local,OU=Postgres,DC=lab,DC=local
OU=postgre2.lab.local,OU=Postgres,DC=lab,DC=local
...

Following the example in the documentation, I tried to create three groups (readers, writers, owners) and map identities based on membership in these groups. Initially, when I was dealing with just one instance, I had the groups readers, writers, owners, and mapped them as follows:

Note the use of sAMAccountName instead of cn in the parent: as recommended in the documentation. When I tried to use cn, ldap2pg didn't work. (see: https://github.com/dalibo/ldap2pg/issues/585)

```
- description: "Search LDAP to create readers, writers, and owners."
  ldapsearch:
    base: OU=postgre1.lab.local,OU=Postgres,DC=lab,DC=local
    filter: "
    (|
      (cn=readers)
      (cn=writers)
      (cn=owners)
    )
    "
  role:
    name: "{member.sAMAccountName}"
    options: LOGIN INHERIT
    parent: "{sAMAccountName.lower()}"
```
Then I wanted to expand this and ran into an issue because AD does not allow groups with the same CN even if they have different DNs. So, I ended up prefixing group names with the OU name:

postgre1.lab.local_readers
postgre1.lab.local_writers
...

However, this broke the previous configuration, understandably. I then tried the following approach:

```
- description: "Search LDAP to create roles from all groups found."
  ldapsearch:
    base: OU=postgre1.lab.local,OU=Postgres,DC=lab,DC=local
    filter: "(objectClass=group)"
  role:
    name: "{member.sAMAccountName}"
    options: LOGIN INHERIT
    parent: "{description.lower()}"
```
Here, I faced the challenge that I was no longer able to map group names (due to the prefix) to roles like readers, writers, and owners. To work around this, I stored the info in the description field, which isn't ideal.

To resolve this issue, a function like replace implemented similarly to functions .lower() and .upper() would be helpful. Then I could do something like:

`parent: "{sAMAccountName.replace(OU+'_','')}"`

Or some other mechanism to achieve prefix stripping, maybe using .split('_')[-1].

Is there already a procedure to solve this? I didn't find anything in the documentation, and I couldn't find any real-world usage examples either.

Thank you for any information.
