### ISSUE TITLE
endless loop when trying to create roles with parent

### ISSUE THREAD

**Issue by pneun87** [dalibo/ldap2pg#592]
Hi all.
I tried to setup ldap2pg to synchronize user and groups with LDAP.
There is a group within LDAP that contains all the users.

These group and the member users shall be created in Postgres, the privileges shall be assigned to the Postgres group.

Even when trying to run this heavily reduced ldap2pg.yml, the system goes into an endless loop and seems to build some memory structures until it gets killed by the oom_killer.

## ldap2pg.yml
``` yaml
version: 6

postgres:
  schemas_query: |
    SELECT nspname FROM pg_catalog.pg_namespace
    WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'
    ORDER BY 1;

privileges:
  schemause:
  - default: global
    type: USAGE
    on: SCHEMAS

  reading:
  - schemause
  - default: global
    type: SELECT
    on: TABLES

rules:
- description: "Setup static roles and grants"
  roles:
  - name: pgro_dev_sys4
    options: NOLOGIN
  grant:
    - privilege: reading
      role: pgro_dev_sys4

- description: "Query LDAP to get members of readers"
  ldapsearch:
    base: "cn=groups,dc=sf-rz,dc=de"
    filter: "(cn=pgro_dev_sys4)"
  role:
    name: '{member.uid}'
    options:
      LOGIN: yes
      CONNECTION LIMIT: 5
    comment: "From LDAP group {dn}."
    parent: "{cn}"
```

## Expectations

- What you expected from ldap2pg ?
1. create the group role pgro_dev_sys4
2. put all the LDAP members of pgro_dev_sys4 into the Postgres group role

- What ldap2pg did wrong ?
Went into an endless loop until killed by the oom_killer.

## Verbose output of ldap2pg execution
time=2024-03-11T16:19:14.269+01:00 level=INFO msg="Starting ldap2pg" version=v6.0 runtime=go1.20.5 commit=023e6933
time=2024-03-11T16:19:14.270+01:00 level=INFO msg="Using YAML configuration file." path=/opt/schufa/pgsql/data/home/pginst_dev_sys4/ldap2pg/ldap2pg-mini.yml
time=2024-03-11T16:19:14.270+01:00 level=DEBUG msg="Loading YAML configuration."
..... (a lot of internal information, the personal userids show up from LDAP)
time=2024-03-11T16:19:14.461+01:00 level=DEBUG msg="Managing role." role=pgldap_dev_sys4
time=2024-03-11T16:19:14.461+01:00 level=DEBUG msg="Managing role." role=pgro_dev_sys4
time=2024-03-11T16:19:14.461+01:00 level=DEBUG msg="Managing role." role=public
time=2024-03-11T16:19:14.461+01:00 level=DEBUG msg="Managing role." role=schean
time=2024-03-11T16:19:14.461+01:00 level=WARN msg="Dry run. Postgres instance will be untouched."

Then no more output until the process is killed.

As soon as the line parent: "{cn}" is removed from the yaml, ldap2pg comes to an end but does not assign the personal users to the group role in PostgreSQL.
