### ISSUE TITLE
Own Priviliges in Version 6.1 ?

### ISSUE THREAD

**Issue by peteerwhite** [dalibo/ldap2pg#664]
Hello everyone,

is there a possibility to define own privileges in version 6.1 (like in version 5) ? 

For example like this:

`privileges:
  my_own_priv:

    type: nspacl
    grant: GRANT EXECUTE ON FUNCTION {schema}.myfunc TO {role};
    revoke: REVOKE EXECUTE ON FUNCTION {schema}.myfunc TO {role};
    inspect: |
      WITH grants AS (
        SELECT
          pronamespace, proname, 
          (aclexplode(proacl)).grantee,
          (aclexplode(proacl)).privilege_type
        FROM pg_proc
      )
      SELECT
        nspname,
        pg_catalog.pg_get_userbyid(grantee) AS grantee,
      FROM grants
      JOIN pg_namespace ON pg_namespace.oid = pronamespace
      WHERE proname = 'myfunc' AND privilege_type = 'EXECUTE';`

Thanks for help :)

**Comment by bersace** [comment]
It's not possible yet. It's a known regression from v5.

However, it's likely to comme back like this:

``` yaml
acl:
  FUNCTION:
    inspect: ...
    grant: ...
    revoke: ...

privileges:
  ro:
    - type: EXECUTE
      on: FUNCTION
```

This new way of declaring acl allow to deduplicate execution of inspect.
