### ISSUE TITLE
Panic on empty object in "privileges" block

### ISSUE THREAD

**Issue by saimikiry** [dalibo/ldap2pg#709]
Hello! I tested ldap2pg and found a bug. The problem is as follows:

When using an empty object in the "privileges" block, the program will report a panic. This problem is relevant only for the "privileges" block and is not reproduced in other parts of the configuration file.

## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>

```
postgres:
  ...

privileges:
  empty_data: # Panic! err="interface conversion: interface {} is nil, not []interface {}"

  # Define `ro` privilege group with read-only grants
  ro:
    - __connect__
    - __select_on_tables__
    - __select_on_sequences__
    - __usage_on_schemas__
    - __usage_on_types__

rules:
  ...
```
</details>

## Expectations

Apparently, this exception is expected to be handled gracefully and not cause panic.

## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary>

![Image](https://github.com/user-attachments/assets/93c4173a-54e3-4f0e-a2b6-9116029ec37e)
</details>
