### ISSUE TITLE
Out of memory due to configuration file error

### ISSUE THREAD

**Issue by saimikiry** [dalibo/ldap2pg#712]
Hello! I would like to draw your attention to the possibility of a OOM (out of memory) if an error is made in the configuration file. If the list of rules contains a role with the same name and parent, an infinite loop will occur.

## ldap2pg.yml
<details><summary>ldap2pg.yml</summary>

```
postgres:
  ...

rules:
- description: "Setup static roles and grants."
  roles:
  - names:
    - readers
    options: NOLOGIN
  - name: writers
    # Grant reading to writers
    parent: readers
    options: NOLOGIN
  - name: owners
    # Grant read/write to owners
    parent: writers
    options: NOLOGIN

  #name field and parent field are the same
  - name: inf_loop
    parent: inf_loop
    options: NOLOGIN
```
</details>

## Expectations

There probably needs to be a mechanism to resolve situations like this.

## top util screen

<details><summary>top util screen</summary>

![Image](https://github.com/user-attachments/assets/8cdf2019-87d4-49e5-9e0a-f326e288ba2b)
</details>
