### ISSUE TITLE
Add whitelist

### ISSUE THREAD

**Issue by julmon** [dalibo/ldap2pg#88]
Hi,

We need to filter out the list of PG roles (returned by `SyncManager.fetch_pg_roles()`) by group (parent) name.

Maybe we could add a new parameter in `postgres` section of the configuration file : `whitelist`

With this parameter, we'll be able to fetch (and sync!!) PG roles only from groups like this:
``` yaml
postgres:
   ...
  blacklist: [*]
  whitelist:
     groups: [MyGroup1, foo*]
     users: []
```

Thoughts ?

**Comment by bersace** [comment]
Some comments:

- what is the acutal purpose/use case of this feature ? (The why, not the how). Some background would be useful to design the best proposal together.
- ldap2pg does not manage *group* or *users*, only roles. That's a new concept in ldap2pg. How do you distinguish groups from users ? A role with `LOGIN` can have members too. There is no technical restriction.
- when you whitelist a role, do you intend to whitelist members of each roles, recursively ?

**Comment by bersace** [comment]
Actually, you can just now write a whitelist with *static* roles, like this:

``` yaml
sync_map:
- roles:
  - MyGroup1
  - foo
```

This can't managed wildcard.
